FAULT_CODES = {
    0: "Lỗi giao tiếp nội bộ 1",
    1: "Lỗi mô hình",
    8: "Lỗi giao tiếp CAN song song",
    9: "Mất host",
    10: "Công suất định mức không khớp",
    11: "Cài đặt AC hoặc an toàn không nhất quán",
    12: "Ngắn mạch UPS",
    13: "Dòng ngược UPS",
    14: "Ngắn mạch BUS",
    15: "Pha bất thường trong hệ thống 3 pha",
    16: "Lỗi relay",
    17: "Lỗi giao tiếp nội bộ 2",
    18: "Lỗi giao tiếp nội bộ 3",
    19: "Quá áp BUS",
    20: "Lỗi kết nối EPS",
    21: "Quá áp PV",
    22: "Bảo vệ quá dòng",
    23: "Lỗi dây trung tính",
    24: "Ngắn mạch PV",
    25: "Nhiệt độ tản nhiệt ngoài phạm vi",
    26: "Lỗi nội bộ",
    27: "Lỗi không nhất quán",
    28: "Kết nối máy phát không nhất quán",
    29: "Mất tín hiệu đồng bộ song song",
    31: "Lỗi giao tiếp nội bộ 4",
}
