from ..constants.hold_registers import *
from ..utils import get_bits, set_bits

SELECTBOX_TYPES = [
    {
        "name": "Chế độ sạc AC",
        "register": H_SYSTEM_ENABLE_2,   # 120
        "register_type": "hold",
        "extract": lambda reg: get_bits(reg, 1, 3),
        "compose": lambda orig, value: set_bits(orig, 1, 3, value),
        "options": {
            0: "Tắt",
            1: "Theo thời gian",
            2: "Theo điện áp",
            3: "Theo SOC",
            4: "Theo điện áp và thời gian",
            5: "Theo SOC và thời gian",
        },
        "icon": "mdi:battery-charging",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Chế độ điều khiển xả",
        "register": H_SYSTEM_ENABLE_2,   # 120
        "register_type": "hold",
        "extract": lambda reg: get_bits(reg, 4, 2),
        "compose": lambda orig, value: set_bits(orig, 4, 2, value),
        "options": {
            0: "Theo điện áp",
            1: "Theo SOC",
            2: "Theo cả hai",
        },
        "icon": "mdi:battery-arrow-down",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Kiểu dừng xả (On-Grid)",
        "register": H_SYSTEM_ENABLE_2,   # 120
        "register_type": "hold",
        "extract": lambda reg: get_bits(reg, 6, 1),
        "compose": lambda orig, value: set_bits(orig, 6, 1, value),
        "options": {
            0: "Theo điện áp",
            1: "Theo SOC",
        },
        "icon": "mdi:grid",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lưới điện",
    },
    {
        "name": "Kiểu sạc từ máy phát",
        "register": H_SYSTEM_ENABLE_2,   # 120
        "register_type": "hold",
        "extract": lambda reg: get_bits(reg, 7, 1),
        "compose": lambda orig, value: set_bits(orig, 7, 1, value),
        "options": {
            0: "According to Battery Voltage",
            1: "According to Battery SOC",
        },
        "icon": "mdi:engine",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Máy phát",
    },
    {
        "name": "Cấu hình hệ thống",
        "register": H_SET_SYSTEM_TYPE,    # 112
        "register_type": "hold",
        "extract": lambda reg: reg,
        "compose": lambda orig, value: value,
        "options": {
            0: "Không song song (đơn)",
            1: "Song song 1 pha (chính)",
            2: "Phụ",
            3: "Song song 3 pha (Master)",
            4: "2×208V (Master) - pha tách",
        },
        "icon": "mdi:vector-link",
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Ngôn ngữ",
        "register": H_LANGUAGE_AND_DEVICE_TYPE, # 16
        "register_type": "hold",
        "extract": lambda reg: reg,
        "compose": lambda orig, value: value,
        "options": {
            0: "Tiếng Anh",
            1: "Tiếng Đức",
        },
        "icon": "mdi:translate",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Cấu hình đầu vào PV",
        "register": H_PV_INPUT_MODEL, # 20
        "register_type": "hold",
        "extract": lambda reg: reg,
        "compose": lambda orig, value: value,
        "options": {
            0: "Không có PV",
            1: "PV1 vào",
            2: "PV2 vào",
            3: "PV3 vào",
            4: "PV1 & PV2 vào",
            5: "PV1 & PV3 vào",
            6: "PV2 & PV3 vào",
            7: "PV1 & PV2 & PV3 vào",
        },
        "icon": "mdi:solar-panel",
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin mặt trời",
    },
    {
        "name": "Kiểu lệnh công suất phản kháng",
        "register": H_REACTIVE_POWER_CMD_TYPE, # 59
        "register_type": "hold",
        "extract": lambda reg: reg,
        "compose": lambda orig, value: value,
        "options": {
            0: "Hệ số công suất đơn vị",
            1: "PF cố định",
            2: "Đường cong PF mặc định Q(P)",
            3: "Đường cong PF tùy chỉnh",
            4: "% công suất phản kháng dung",
            5: "% công suất phản kháng cảm",
            6: "Đường cong Q(V)",
            7: "Q(V) Động",
        },
        "icon": "mdi:flash",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lưới điện",
    },
    {
        "name": "Cấu hình ưu tiên đầu ra",
        "register": H_OUTPUT_PRIORITY_CONFIG, # 145
        "register_type": "hold",
        "extract": lambda reg: reg,
        "compose": lambda orig, value: value,
        "options": {
            0: "Ưu tiên pin",
            1: "Ưu tiên PV",
            2: "Ưu tiên AC",
        },
        "icon": "mdi:power-plug",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Chế độ đường dây",
        "register": H_LINE_MODE, # 146
        "register_type": "hold",
        "extract": lambda reg: reg,
        "compose": lambda orig, value: value,
        "options": {
            0: "APL (Thiết bị)",
            1: "UPS (Lưu điện)",
            2: "GEN (Máy phát)",
        },
        "icon": "mdi:power-settings",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Loại lưới điện",
        "register": H_GRID_TYPE, # 205
        "register_type": "hold",
        "icon": "mdi:transmission-tower",
        "extract": lambda reg: reg,
        "compose": lambda orig, value: value,
        "options": {
            # Standard Types
            0: "Pha tách 240V/120V",
            1: "3 pha sao 120V/208V",
            2: "1 pha 240V",
            3: "1 pha 230V",
            4: "Pha tách 200V/100V",
            # New Three-Phase Types
            5: "3 pha tam giác 230V/230V",
            6: "3 pha sao 240V/415V",
            7: "3 pha sao 230V/400V",
            8: "3 pha sao 220V/380V"
        },
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lưới điện",
    },
    {
        "name": "Chế độ hoạt động",
        "register": H_FUNCTION_ENABLE_1, # 21
        "register_type": "hold",
        "extract": lambda reg: get_bits(reg, 9, 1),
        "compose": lambda orig, value: set_bits(orig, 9, 1, value),
        "options": {
            0: "Chờ",
            1: "Bình thường",
        },
        "icon": "mdi:power-settings",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Kích hoạt tải thông minh",
        "register": H_FUNCTION_ENABLE_4, # 179
        "register_type": "hold",
        "extract": lambda reg: get_bits(reg, 13, 1),
        "compose": lambda orig, value: set_bits(orig, 13, 1, value),
        "options": {
            0: "Máy phát",
            1: "Tải thông minh",
        },
        "icon": "mdi:home-lightning-bolt",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Loại màn hình LCD",
        "register": H_LCD_CONFIG, # 224
        "register_type": "hold",
        "extract": lambda reg: get_bits(reg, 8, 1),
        "compose": lambda orig, value: set_bits(orig, 8, 1, value),
        "options": {
            0: "Màn hình cỡ 'B'",
            1: "Màn hình cỡ 'S'",
        },
        "icon": "mdi:monitor",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Điện áp EPS",
        "register": H_EPS_VOLTAGE_SET,
        "register_type": "hold",
        "icon": "mdi:power-socket-us",
        "extract": lambda value: value,
        "compose": lambda orig, value: value,
        "options": {
            208: "208 V",
            220: "220 V",
            230: "230 V",
            240: "240 V",
            277: "277 V"
        },
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "EPS (Off-Grid)",
    },
    {
        "name": "Tần số EPS",
        "register": H_EPS_FREQ_SET,
        "register_type": "hold",
        "icon": "mdi:sine-wave",
        "extract": lambda value: value,
        "compose": lambda orig, value: value,
        "options": {
            50: "50 Hz",
            60: "60 Hz"
        },
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "EPS (Off-Grid)",
    },
    {
        "name": "Pha ghép (Off-Grid)",
        "register": H_SET_COMPOSED_PHASE,
        "register_type": "hold",
        "icon": "mdi:chart-timeline-variant",
        "extract": lambda value: value & 0xFF,
        "compose": lambda orig, value: value,
        "options": {
            1: "Pha R",
            2: "Pha S",
            3: "Pha T"
        },
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Lưới điện",
    },
] 