#
# entity_descriptions/sensor_types.py
#

from ..constants.input_registers import *
from ..constants.hold_registers import H_NO_FULL_CHG_DAY_CONFIG, H_BOOTLOADER_VERSION_AND_FLAG
from ..constants.battery_registers import *
from ..constants.fault_codes import FAULT_CODES
from ..constants.warning_codes import WARNING_CODES
from ..const import CONF_RATED_POWER
from ..utils import decode_bitmask_to_string, get_highest_set_bit

SENSOR_TYPES = [
    # --- Calculated Sensors ---
    {
        "name": "Tỷ lệ tải",
        "register_type": "calculated",
        "depends_on": [I_STATE, I_PLOAD, I_PEPS],
        "unit": "%",
        "device_class": "power_factor",
        "state_class": "measurement",
        "icon": "mdi:gauge",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "extract": lambda registers, entry: (
            (
                round((registers.get(I_PEPS, 0) / rated_power) * 100, 2)
                if registers.get(I_STATE) == 64
                else round((registers.get(I_PLOAD, 0) / rated_power) * 100, 2)
            ) if (rated_power := entry.data.get(CONF_RATED_POWER)) and rated_power > 0 else 0
        ),
        "master_only": False,
    },
    {
        "name": "Luồng năng lượng",
        "register_type": "calculated",
        "depends_on": [I_PDISCHARGE, I_PTOUSER, I_PTOUSER_S, I_PTOUSER_T, I_PTOUSER_L1N, I_PTOUSER_L2N, I_PPV1, I_PPV2, I_PPV3, I_PPV4, I_PPV5, I_PPV6],
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:transmission-tower-export",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "extract": lambda registers, entry: (
            lambda battery_discharge, grid_power_total, pv_total: (
                pv_total + grid_power_total - battery_discharge
            )
        )(
            registers.get(I_PDISCHARGE, 0),
            sum(registers.get(grid_reg, 0) for grid_reg in [I_PTOUSER, I_PTOUSER_S, I_PTOUSER_T, I_PTOUSER_L1N, I_PTOUSER_L2N]),
            sum(registers.get(pv_reg, 0) for pv_reg in [I_PPV1, I_PPV2, I_PPV3, I_PPV4, I_PPV5, I_PPV6])
        ),
        "master_only": False,
    },
    {
        "name": "Luồng pin",
        "register_type": "calculated",
        "depends_on": [I_PCHARGE, I_PDISCHARGE],
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:battery-sync",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "extract": lambda registers, entry: (
            registers.get(I_PDISCHARGE, 0) - registers.get(I_PCHARGE, 0)
        ),
        "master_only": False,
        "device_group": "Pin",
    },
    {
        "name": "Luồng lưới",
        "register_type": "calculated",
        "depends_on": [I_PTOGRID, I_PTOUSER],
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:transmission-tower",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "extract": lambda registers, entry: (
            registers.get(I_PTOUSER, 0) - registers.get(I_PTOGRID, 0)
        ),
        "master_only": False,
        "device_group": "Lưới điện",
    },

    # --- State Sensors ---
    {
        "name": "Trạng thái biến tần",
        "register": I_STATE,
        "register_type": "input",
        "extract": lambda value: value,
        "icon": "mdi:state-machine",
        "enabled": True,
        "visible": True,
        "default": "Unknown State",
        "options": {
            0: "Chờ",
            1: "Lỗi",
            2: "Lập trình / Cập nhật",
            4: "PV cấp tải - Phát dư lên lưới",
            8: "PV cấp tải & sạc pin",
            12: "PV cấp tải, sạc pin & phát lưới",
            16: "Pin xả tải - Phát dư lên lưới",
            17: "Chờ",
            20: "PV & pin cấp tải - Phát dư lên lưới",
            32: "Lưới sạc pin",
            40: "Lưới & PV sạc pin",
            64: "Off-Grid: Pin cấp tải",
            96: "Off-Grid: AC Coupling PV sạc pin",
            128: "Off-Grid: PV không ổn định (Cấm)",
            136: "Off-Grid: PV cấp tải & sạc pin",
            192: "Off-Grid: PV & pin cấp tải",
        },
        "master_only": False,
    },
    {
        "name": "Mã trạng thái biến tần",
        "register": I_STATE,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1.0,
        "icon": "mdi:numeric",
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Loại đầu vào AC",
        "register": I_AC_INPUT_TYPE_FLAGS,
        "register_type": "input",
        "extract": lambda value: value & 1, # Extracts Bit 0 from the register
        "icon": "mdi:power-source",
        "enabled": True,
        "visible": True,
        "default": "Lưới điện",
        "options": {
            0: "Lưới điện", # 0 indicates Grid input
            1: "Máy phát" # 1 indicates Generator input
        },
        "master_only": False,
    },

    # --- Core Status & PV Information ---
    {
        "name": "Điện áp PV1",
        "register": I_VPV1,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin mặt trời",
    },
    {
        "name": "Công suất PV1",
        "register": I_PPV1,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin mặt trời",
    },
    {
        "name": "Dòng điện PV1",
        "register_type": "calculated",
        "depends_on": [I_PPV1, I_VPV1],
        "extract": lambda registers, entry: (
            round(registers.get(I_PPV1, 0) / (registers.get(I_VPV1, 0) * 0.1), 2)
            if registers.get(I_VPV1, 0) > 0 else 0
        ),
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 2,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin mặt trời",
    },
    {
        "name": "Điện áp PV2",
        "register": I_VPV2,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin mặt trời",
    },
    {
        "name": "Công suất PV2",
        "register": I_PPV2,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin mặt trời",
    },
    {
        "name": "Dòng điện PV2",
        "register_type": "calculated",
        "depends_on": [I_PPV2, I_VPV2],
        "extract": lambda registers, entry: (
            round(registers.get(I_PPV2, 0) / (registers.get(I_VPV2, 0) * 0.1), 2)
            if registers.get(I_VPV2, 0) > 0 else 0
        ),
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 2,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin mặt trời",
    },
    {
        "name": "Điện áp PV3",
        "register": I_VPV3,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin mặt trời",
    },
    {
        "name": "Công suất PV3",
        "register": I_PPV3,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin mặt trời",
    },
    {
        "name": "Dòng điện PV3",
        "register_type": "calculated",
        "depends_on": [I_PPV3, I_VPV3],
        "extract": lambda registers, entry: (
            round(registers.get(I_PPV3, 0) / (registers.get(I_VPV3, 0) * 0.1), 2)
            if registers.get(I_VPV3, 0) > 0 else 0
        ),
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 2,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin mặt trời",
    },
    {
        "name": "Điện áp PV4",
        "register": I_VPV4,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin mặt trời",
    },
    {
        "name": "Công suất PV4",
        "register": I_PPV4,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin mặt trời",
    },
    {
        "name": "Dòng điện PV4",
        "register_type": "calculated",
        "depends_on": [I_PPV4, I_VPV4],
        "extract": lambda registers, entry: (
            round(registers.get(I_PPV4, 0) / (registers.get(I_VPV4, 0) * 0.1), 2)
            if registers.get(I_VPV4, 0) > 0 else 0
        ),
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 2,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin mặt trời",
    },
    {
        "name": "Điện áp PV5",
        "register": I_VPV5,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin mặt trời",
    },
    {
        "name": "Công suất PV5",
        "register": I_PPV5,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin mặt trời",
    },
    {
        "name": "Dòng điện PV5",
        "register_type": "calculated",
        "depends_on": [I_PPV5, I_VPV5],
        "extract": lambda registers, entry: (
            round(registers.get(I_PPV5, 0) / (registers.get(I_VPV5, 0) * 0.1), 2)
            if registers.get(I_VPV5, 0) > 0 else 0
        ),
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 2,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin mặt trời",
    },
    {
        "name": "Điện áp PV6",
        "register": I_VPV6,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin mặt trời",
    },
    {
        "name": "Công suất PV6",
        "register": I_PPV6,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin mặt trời",
    },
    {
        "name": "Dòng điện PV6",
        "register_type": "calculated",
        "depends_on": [I_PPV6, I_VPV6],
        "extract": lambda registers, entry: (
            round(registers.get(I_PPV6, 0) / (registers.get(I_VPV6, 0) * 0.1), 2)
            if registers.get(I_VPV6, 0) > 0 else 0
        ),
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 2,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin mặt trời",
    },
    {
        "name": "Tổng công suất PV",
        "register_type": "calculated",
        "depends_on": [I_PPV1, I_PPV2, I_PPV3, I_PPV4, I_PPV5, I_PPV6],
        "extract": lambda registers, entry: (
            registers.get(I_PPV1, 0) + registers.get(I_PPV2, 0) + registers.get(I_PPV3, 0)
            + registers.get(I_PPV4, 0) + registers.get(I_PPV5, 0) + registers.get(I_PPV6, 0)
        ),
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:solar-power-variant",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin mặt trời",
    },

    # --- Battery Information ---
    {
        "name": "Điện áp pin",
        "register": I_VBAT,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:car-battery",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Pin",
    },
    {
        "name": "SOC pin",
        "register": I_SOC_SOH,
        "register_type": "input",
        "extract": lambda value: value & 0xFF,
        "unit": "%",
        "device_class": "battery",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:battery-high",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Pin",
    },
    {
        "name": "SOH pin",
        "register": I_SOC_SOH,
        "register_type": "input",
        "extract": lambda value: (value >> 8) & 0xFF,
        "unit": "%",
        "device_class": None,
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:battery-heart-variant",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Pin",
    },
    {
        "name": "Số ngày kể từ SOC >= 99",
        "register": H_NO_FULL_CHG_DAY_CONFIG,
        "register_type": "hold",
        "extract": lambda value: value & 0xFF,
        "unit": "d",
        "device_class": "duration",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:battery-heart-variant",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Pin",
    },
    {
        "name": "Phiên bản Bootloader",
        "register": H_BOOTLOADER_VERSION_AND_FLAG,
        "register_type": "hold",
        "extract": lambda value: value & 0xFF,
        "unit": "",
        "device_class": None,
        "state_class": None,
        "scale": 1.0,
        "icon": "mdi:chip",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Cờ cập nhật Bootloader",
        "register": H_BOOTLOADER_VERSION_AND_FLAG,
        "register_type": "hold",
        "extract": lambda value: (value >> 8) & 0xFF,
        "unit": "",
        "device_class": None,
        "state_class": None,
        "scale": 1.0,
        "icon": "mdi:update",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Công suất sạc pin",
        "register": I_PCHARGE,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:battery-arrow-up",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin",
    },
    {
        "name": "Công suất xả pin",
        "register": I_PDISCHARGE,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:battery-arrow-down",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin",
    },
    {
        "name": "Nhiệt độ pin",
        "register": I_TBAT,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:thermometer",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Pin",
    },

    # --- Grid Information ---
    {
        "name": "Điện áp lưới",
        "register": I_VAC_R,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:transmission-tower",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Lưới điện",
    },
    {
        "name": "Điện áp lưới pha S",
        "register": I_VAC_S,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:transmission-tower",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Lưới điện",
    },
    {
        "name": "Điện áp lưới pha T",
        "register": I_VAC_T,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:transmission-tower",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Lưới điện",
    },
    {
        "name": "Tần số lưới",
        "register": I_FAC,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "Hz",
        "device_class": "frequency",
        "state_class": "measurement",
        "scale": 0.01,
        "icon": "mdi:sine-wave",
        "suggested_display_precision": 2,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Lưới điện",
    },
    {
        "name": "Điện áp lưới L1N",
        "register": I_GRID_VOLT_L1N,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:transmission-tower",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Lưới điện",
    },
    {
        "name": "Điện áp lưới L2N",
        "register": I_GRID_VOLT_L2N,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:transmission-tower",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Lưới điện",
    },
    {
        "name": "Công suất biến tần",
        "register": I_PINV,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:power-plug",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Công suất biến tần L1N",
        "register": I_PINV_L1N,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:power-plug",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Công suất biến tần L2N",
        "register": I_PINV_L2N,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:power-plug",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Dòng biến tần",
        "register": I_IINV_RMS,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
        "scale": 0.01,
        "icon": "mdi:current-ac",
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Công suất chỉnh lưu sạc AC",
        "register": I_PREC,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:power-plug",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Công suất chỉnh lưu AC L1N",
        "register": I_PREC_L1N,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:power-plug",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Công suất chỉnh lưu AC L2N",
        "register": I_PREC_L2N,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:power-plug",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Công suất AC Coupling",
        "register": I_AC_COUPLE_POWER,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:power-plug",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "AC Coupling",
    },
    {
        "name": "Công suất AC Coupling pha S",
        "register": I_AC_COUPLE_POWER_S,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:power-plug",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "AC Coupling",
    },
    {
        "name": "Công suất AC Coupling pha T",
        "register": I_AC_COUPLE_POWER_T,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:power-plug",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "AC Coupling",
    },
    {
        "name": "Hệ số công suất",
        "register": I_PF,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "%",
        "device_class": "power_factor",
        "state_class": "measurement",
        "scale": 0.001,
        "icon": "mdi:angle-acute",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
         "name": "Công suất phản kháng",
         "register": I_QINV,
         "register_type": "input",
         "extract": lambda value: value if value < 32768 else value - 65536,
         "unit": "var",
         "device_class": "reactive_power",
         "state_class": "measurement",
         "scale": 1.0,
         "icon": "mdi:flash",
         "suggested_display_precision": 0,
         "enabled": True,
         "visible": True,
         "master_only": False,
     },
    {
        "name": "Công suất phát lưới",
        "register": I_PTOGRID,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:transmission-tower-export",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Lưới điện",
    },
    {
        "name": "Công suất phát lưới L1N",
        "register": I_PTOGRID_L1N,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:transmission-tower-export",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Lưới điện",
    },
    {
        "name": "Công suất phát lưới L2N",
        "register": I_PTOGRID_L2N,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:transmission-tower-export",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Lưới điện",
    },
    {
        "name": "Công suất nhập lưới",
        "register": I_PTOUSER,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:transmission-tower-import",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Lưới điện",
    },
    {
        "name": "Công suất nhập lưới L1N",
        "register": I_PTOUSER_L1N,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:transmission-tower-import",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Lưới điện",
    },
    {
        "name": "Công suất nhập lưới L2N",
        "register": I_PTOUSER_L2N,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:transmission-tower-import",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Lưới điện",
    },
    {
        "name": "Công suất tải",
        "register": I_PLOAD,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:home-lightning-bolt",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Công suất tải (On-Grid)",
        "register": I_ONGRID_LOAD_POWER,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:home-lightning-bolt-outline",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Lưới điện",
    },
    {
        "name": "Công suất tải thông minh",
        "register": I_SMART_LOAD_POWER,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:home-lightning-bolt-outline",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },

    # --- EPS (Off-Grid) Information ---
    {
        "name": "Điện áp EPS",
        "register": I_VEPS_R,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:power-plug-off",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "EPS (Off-Grid)",
    },
    {
        "name": "Điện áp EPS L1N",
        "register": I_EPS_VOLT_L1N,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:power-plug-off",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "EPS (Off-Grid)",
    },
    {
        "name": "Điện áp EPS L2N",
        "register": I_EPS_VOLT_L2N,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:power-plug-off",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "EPS (Off-Grid)",
    },
    {
        "name": "Điện áp EPS pha S",
        "register": I_VEPS_S,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:power-plug-off",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "EPS (Off-Grid)",
    },
    {
        "name": "Điện áp EPS pha T",
        "register": I_VEPS_T,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:power-plug-off",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "EPS (Off-Grid)",
    },
    {
        "name": "Tần số EPS",
        "register": I_FEPS,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "Hz",
        "device_class": "frequency",
        "state_class": "measurement",
        "scale": 0.01,
        "icon": "mdi:sine-wave",
        "suggested_display_precision": 2,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "EPS (Off-Grid)",
    },
    {
        "name": "Công suất EPS",
        "register": I_PEPS,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:power-plug-off",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "EPS (Off-Grid)",
    },
    {
        "name": "Công suất EPS L1N",
        "register": I_PEPS_L1N,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:power-plug-off",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "EPS (Off-Grid)",
    },
    {
        "name": "Công suất EPS L2N",
        "register": I_PEPS_L2N,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:power-plug-off",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "EPS (Off-Grid)",
    },
    {
        "name": "Công suất biểu kiến EPS",
        "register": I_SEPS,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "VA",
        "device_class": "apparent_power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:power-plug-off",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "EPS (Off-Grid)",
    },
    {
        "name": "Công suất biểu kiến EPS L1N",
        "register": I_SEPS_L1N,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "VA",
        "device_class": "apparent_power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:power-plug-off",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "EPS (Off-Grid)",
    },
    {
        "name": "Công suất biểu kiến EPS L2N",
        "register": I_SEPS_L2N,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "VA",
        "device_class": "apparent_power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:power-plug-off",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "EPS (Off-Grid)",
    },

    # --- Daily Energy ---
    {
        "name": "Sản lượng PV1 hôm nay",
        "register": I_EPV1_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin mặt trời",
    },
    {
        "name": "Sản lượng PV2 hôm nay",
        "register": I_EPV2_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin mặt trời",
    },
    {
        "name": "Sản lượng PV3 hôm nay",
        "register": I_EPV3_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin mặt trời",
    },
    {
        "name": "Sản lượng PV4 hôm nay",
        "register": I_EPV4_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin mặt trời",
    },
    {
        "name": "Sản lượng PV5 hôm nay",
        "register": I_EPV5_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin mặt trời",
    },
    {
        "name": "Sản lượng PV6 hôm nay",
        "register": I_EPV6_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin mặt trời",
    },
    {
        "name": "Tổng sản lượng PV hôm nay",
        "register_type": "calculated",
        "depends_on": [I_EPV1_DAY, I_EPV2_DAY, I_EPV3_DAY, I_EPV4_DAY, I_EPV5_DAY, I_EPV6_DAY],
        "extract": lambda registers, entry: (
            registers.get(I_EPV1_DAY, 0) + registers.get(I_EPV2_DAY, 0) + registers.get(I_EPV3_DAY, 0)
            + registers.get(I_EPV4_DAY, 0) + registers.get(I_EPV5_DAY, 0) + registers.get(I_EPV6_DAY, 0)
        ),
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:solar-power-variant",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin mặt trời",
    },
    {
        "name": "Sản lượng biến tần hôm nay",
        "register": I_EINV_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:power-plug",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Điện sạc AC hôm nay",
        "register": I_EREC_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:power-plug",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Điện sạc pin hôm nay",
        "register": I_ECHG_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:battery-arrow-up-box",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Điện xả pin hôm nay",
        "register": I_EDISCHG_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:battery-arrow-down-box",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Sản lượng EPS hôm nay",
        "register": I_EEPS_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:power-plug-off",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "EPS (Off-Grid)",
    },
    {
        "name": "Sản lượng EPS L1N hôm nay",
        "register": I_EEPS_L1N_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:power-plug-off",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "EPS (Off-Grid)",
    },
    {
        "name": "Sản lượng EPS L2N hôm nay",
        "register": I_EEPS_L2N_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:power-plug-off",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "EPS (Off-Grid)",
    },
    {
        "name": "Điện phát lưới hôm nay",
        "register": I_ETOGRID_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:home-export-outline",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Lưới điện",
    },
    {
        "name": "Điện nhập lưới hôm nay",
        "register": I_ETOUSER_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:home-import-outline",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Lưới điện",
    },
    {
        "name": "Sản lượng máy phát hôm nay",
        "register": I_EGEN_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:engine",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Máy phát",
    },
    {
        "name": "Điện tiêu thụ tải hôm nay",
        "register": I_ELOAD_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:home-lightning-bolt",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },

    # --- System, Temperature & Generator ---
    {
        "name": "Nhiệt độ nội bộ",
        "register": I_TINNER,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:thermometer",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Nhiệt độ nội bộ 2",
        "register": I_TEMP_NTC_FOR_INDC,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:thermometer",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Nhiệt độ tản nhiệt",
        "register": I_TRADIATOR1,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:fan",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Nhiệt độ tản nhiệt 2",
        "register": I_TRADIATOR2,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:fan",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Nhiệt độ tản nhiệt 3",
        "register": I_TEMP_NTC_FOR_DCDCL,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:fan",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Nhiệt độ tản nhiệt 4",
        "register": I_TEMP_NTC_FOR_DCDCH,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:fan",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Điện áp máy phát",
        "register": I_GEN_VOLT,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:engine",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Máy phát",
    },
    {
        "name": "Điện áp máy phát L1N",
        "register": I_GEN_VOLT_L1N,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:engine",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Máy phát",
    },
    {
        "name": "Điện áp máy phát L2N",
        "register": I_GEN_VOLT_L2N,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:engine",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Máy phát",
    },
    {
        "name": "Tần số máy phát",
        "register": I_GEN_FREQ,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "Hz",
        "device_class": "frequency",
        "state_class": "measurement",
        "scale": 0.01,
        "icon": "mdi:engine",
        "suggested_display_precision": 2,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Máy phát",
    },
    {
        "name": "Công suất máy phát",
        "register": I_GEN_POWER,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:engine",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Máy phát",
    },
    {
        "name": "Thời gian sạc 1 chạm còn lại",
        "register": I_REMAINING_CHARGE_TIME,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "min",
        "device_class": "duration",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:timer-sand",
        "enabled": True,
        "visible": True,
        "master_only": False,
    },

    # --- System & Bus Voltages ---
    {
        "name": "Điện áp Bus 1",
        "register": I_VBUS1,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1, # Unit is 0.1V
        "icon": "mdi:bus-school",
        "suggested_display_precision": 1,
        "enabled": True,  # Typically for diagnostics
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Điện áp Bus 2",
        "register": I_VBUS2,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1, # Unit is 0.1V
        "icon": "mdi:bus-school",
        "suggested_display_precision": 1,
        "enabled": True, # Typically for diagnostics
        "visible": True, 
        "master_only": False,
    },
    {
        "name": "Điện áp nửa Bus",
        "register": I_VBUS_P,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1, # Unit is 0.1V
        "icon": "mdi:bus-school",
        "suggested_display_precision": 1,
        "enabled": True, # Typically for diagnostics
        "visible": True,
        "master_only": False,
    },

    # --- BMS Information ---
    {
        "name": "Dòng sạc tối đa BMS",
        "register": I_BMS_MAX_CHG_CURR,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:battery-lock",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Pin",
    },
    {
        "name": "Dòng xả tối đa BMS",
        "register": I_BMS_MAX_DISCHG_CURR,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:battery-lock",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Pin",
    },
    {
        "name": "Điện áp tham chiếu sạc BMS",
        "register": I_BMS_CHARGE_VOLT_REF,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:battery-sync",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Pin",
    },
    {
        "name": "Điện áp ngừng xả BMS",
        "register": I_BMS_DISCHG_CUT_VOLT,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:battery-sync",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Pin",
    },
    {
        "name": "Số cụm pin song song",
        "register": I_BAT_PARALLEL_NUM,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1.0,
        "icon": "mdi:battery-sync",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Pin",
    },
    {
        "name": "Dung lượng pin",
        "register": I_BAT_CAPACITY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "Ah",
        "device_class": None,
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:car-battery",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Pin",
    },
    {
        "name": "Dòng pin BMS",
        "register": I_BMS_BAT_CURRENT,
        "register_type": "input",
        "extract": lambda value: value if value < 32768 else value - 65536,
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:current-dc",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Pin",
    },
    {
        "name": "Mã lỗi BMS",
        "register": I_BMS_FAULT_CODE,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1.0,
        "icon": "mdi:alert-circle-outline",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Pin",
    },
    {
        "name": "Mã cảnh báo BMS",
        "register": I_BMS_WARNING_CODE,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1.0,
        "icon": "mdi:alert-outline",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Pin",
    },
    {
        "name": "Điện áp cell cao nhất BMS",
        "register": I_BMS_MAX_CELL_VOLT,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.001,
        "icon": "mdi:battery-positive",
        "suggested_display_precision": 3,
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Pin",
    },
    {
        "name": "Điện áp cell thấp nhất BMS",
        "register": I_BMS_MIN_CELL_VOLT,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.001,
        "icon": "mdi:battery-negative",
        "suggested_display_precision": 3,
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Pin",
    },
    {
        "name": "Chênh lệch cell BMS",
        "register_type": "calculated",
        "depends_on": [I_BMS_MIN_CELL_VOLT, I_BMS_MAX_CELL_VOLT],
        "extract": lambda registers, entry: (
            round((registers.get(I_BMS_MAX_CELL_VOLT) - registers.get(I_BMS_MIN_CELL_VOLT)) / 1000.0, 3)
            if registers.get(I_BMS_MAX_CELL_VOLT) is not None and registers.get(I_BMS_MIN_CELL_VOLT) is not None
            else None
        ),
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:car-battery",
        "suggested_display_precision": 3,
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Pin",
    },
    {
        "name": "Nhiệt độ cell cao nhất BMS",
        "register": I_BMS_MAX_CELL_TEMP,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:thermometer-chevron-up",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Pin",
    },
    {
        "name": "Nhiệt độ cell thấp nhất BMS",
        "register": I_BMS_MIN_CELL_TEMP,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:thermometer-chevron-down",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Pin",
    },
    {
        "name": "Số chu kỳ BMS",
        "register": I_BMS_CYCLE_COUNT,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "cycles",
        "device_class": None,
        "state_class": "total_increasing",
        "scale": 1.0,
        "icon": "mdi:battery-sync",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Pin",
    },
    {
        "name": "Trạng thái pin BMS 0",
        "register": I_BMS_BAT_STATUS_0,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1.0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin",
    },
    {
        "name": "Trạng thái pin BMS 1",
        "register": I_BMS_BAT_STATUS_1,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1.0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin",
    },
    {
        "name": "Trạng thái pin BMS 2",
        "register": I_BMS_BAT_STATUS_2,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1.0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin",
    },
    {
        "name": "Trạng thái pin BMS 3",
        "register": I_BMS_BAT_STATUS_3,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1.0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin",
    },
    {
        "name": "Trạng thái pin BMS 4",
        "register": I_BMS_BAT_STATUS_4,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1.0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin",
    },
    {
        "name": "Trạng thái pin BMS 5",
        "register": I_BMS_BAT_STATUS_5,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1.0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin",
    },
    {
        "name": "Trạng thái pin BMS 6",
        "register": I_BMS_BAT_STATUS_6,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1.0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin",
    },
    {
        "name": "Trạng thái pin BMS 7",
        "register": I_BMS_BAT_STATUS_7,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1.0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin",
    },
    {
        "name": "Trạng thái pin BMS 8",
        "register": I_BMS_BAT_STATUS_8,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1.0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin",
    },
    {
        "name": "Trạng thái pin BMS 9",
        "register": I_BMS_BAT_STATUS_9,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1.0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin",
    },
    {
        "name": "Trạng thái pin BMS tổng hợp",
        "register": I_BMS_BAT_STATUS_INV,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1.0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin",
    },
    {
         "name": "Điện áp pin mẫu biến tần",
         "register": I_INV_BAT_VOLT_SAMPLE,
         "register_type": "input",
         "extract": lambda value: value,
         "unit": "V",
         "device_class": "voltage",
         "state_class": "measurement",
         "scale": 0.1,
         "icon": "mdi:battery-scan",
         "suggested_display_precision": 1,
         "enabled": True,
         "visible": True,
         "master_only": True,
        "device_group": "Pin",
     },

    # --- Faults & Warnings ---
    {
        "name": "Mã lỗi nội bộ",
        "register": I_INTERNAL_FAULT,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1.0,
        "icon": "mdi:alert-box-outline",
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Lỗi đang hoạt động (Mã)",
        "register_type": "calculated",
        "depends_on": [I_FAULT_CODE_L, I_FAULT_CODE_H],
        "icon": "mdi:numeric",
        "enabled": True,
        "visible": True,
        "extract": lambda registers, entry: get_highest_set_bit(
            (registers.get(I_FAULT_CODE_H, 0) << 16) | registers.get(I_FAULT_CODE_L, 0)
        ),
        "master_only": False,
    },
    {
        "name": "Lỗi đang hoạt động (Mô tả)",
        "register_type": "calculated",
        "depends_on": [I_FAULT_CODE_L, I_FAULT_CODE_H],
        "icon": "mdi:alert-circle-outline",
        "enabled": True,
        "visible": True,
        "extract": lambda registers, entry: decode_bitmask_to_string(
            (registers.get(I_FAULT_CODE_H, 0) << 16) | registers.get(I_FAULT_CODE_L, 0),
            FAULT_CODES,
            "No Faults"
        ),
        "master_only": False,
    },
    {
        "name": "Cảnh báo đang hoạt động (Mã)",
        "register_type": "calculated",
        "depends_on": [I_WARNING_CODE_L, I_WARNING_CODE_H],
        "icon": "mdi:numeric",
        "enabled": True,
        "visible": True,
        "extract": lambda registers, entry: get_highest_set_bit(
            (registers.get(I_WARNING_CODE_H, 0) << 16) | registers.get(I_WARNING_CODE_L, 0)
        ),
        "master_only": False,
    },
    {
        "name": "Cảnh báo đang hoạt động (Mô tả)",
        "register_type": "calculated",
        "depends_on": [I_WARNING_CODE_L, I_WARNING_CODE_H],
        "icon": "mdi:alert-outline",
        "enabled": True,
        "visible": True,
        "extract": lambda registers, entry: decode_bitmask_to_string(
            (registers.get(I_WARNING_CODE_H, 0) << 16) | registers.get(I_WARNING_CODE_L, 0),
            WARNING_CODES,
            "No Warnings"
        ),
        "master_only": False,
    },

    # --- Parallel Status ---
    {
        "name": "Vai trò song song",
        "register": I_MASTER_SLAVE_PARALLEL_STATUS,
        "register_type": "input",
        "extract": lambda value: value & 3,
        "icon": "mdi:vector-link",
        "enabled": True,
        "visible": True,
        "options": {
            1: "Master",
            2: "Slave",
            3: "Song song bật"
        },
        "default": "Độc lập",
        "master_only": False,
    },
    {
        "name": "Pha song song",
        "register": I_MASTER_SLAVE_PARALLEL_STATUS,
        "register_type": "input",
        "extract": lambda value: (value >> 2) & 3,
        "icon": "mdi:chart-timeline-variant",
        "enabled": True,
        "visible": True,
        "options": {
            1: "Pha R",
            2: "Pha S",
            3: "Pha T"
        },
        "default": "Không xác định",
        "master_only": False,
        "device_group": "Lưới điện",
    },
    {
        "name": "Thứ tự pha",
        "register": I_MASTER_SLAVE_PARALLEL_STATUS,
        "register_type": "input",
        "extract": lambda value: (value >> 4) & 3,
        "icon": "mdi:rotate-3d-variant",
        "enabled": True,
        "visible": True,
        "options": {
            0: "Thuận",
            1: "Nghịch"
        },
        "default": "Không xác định",
        "master_only": False,
        "device_group": "Lưới điện",
    },
    {
        "name": "Số biến tần song song",
        "register": I_MASTER_SLAVE_PARALLEL_STATUS,
        "register_type": "input",
        "extract": lambda value: (value >> 8) & 511,
        "unit": "",
        "device_class": None,
        "scale": 1,
        "icon": "mdi:counter",
        "enabled": True,
        "visible": True,
        "master_only": False,
    },

    # --- Cumulative (Lifetime) Totals ---
    {
        "name": "Tổng thời gian vận hành",
        "register_type": "calculated",
        "depends_on": [I_RUNNING_TIME_L, I_RUNNING_TIME_H],
        "extract": lambda registers, entry: (registers.get(I_RUNNING_TIME_H, 0) << 16) | registers.get(I_RUNNING_TIME_L, 0),
        "unit": "s",
        "device_class": "duration",
        "state_class": "total_increasing",
        "scale": 1.0,
        "icon": "mdi:timer",
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Tổng sản lượng PV1",
        "register_type": "calculated",
        "depends_on": [I_EPV1_ALL_L, I_EPV1_ALL_H],
        "extract": lambda registers, entry: (registers.get(I_EPV1_ALL_H, 0) << 16) | registers.get(I_EPV1_ALL_L, 0),
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin mặt trời",
    },
    {
        "name": "Tổng sản lượng PV2",
        "register_type": "calculated",
        "depends_on": [I_EPV2_ALL_L, I_EPV2_ALL_H],
        "extract": lambda registers, entry: (registers.get(I_EPV2_ALL_H, 0) << 16) | registers.get(I_EPV2_ALL_L, 0),
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin mặt trời",
    },
    {
        "name": "Tổng sản lượng PV3",
        "register_type": "calculated",
        "depends_on": [I_EPV3_ALL_L, I_EPV3_ALL_H],
        "extract": lambda registers, entry: (registers.get(I_EPV3_ALL_H, 0) << 16) | registers.get(I_EPV3_ALL_L, 0),
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin mặt trời",
    },
    {
        "name": "Tổng sản lượng PV4",
        "register_type": "calculated",
        "depends_on": [I_EPV4_ALL_L, I_EPV4_ALL_H],
        "extract": lambda registers, entry: (registers.get(I_EPV4_ALL_H, 0) << 16) | registers.get(I_EPV4_ALL_L, 0),
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin mặt trời",
    },
    {
         "name": "Tổng sản lượng PV5",
         "register_type": "calculated",
         "depends_on": [I_EPV5_ALL_L, I_EPV5_ALL_H],
         "extract": lambda registers, entry: (registers.get(I_EPV5_ALL_H, 0) << 16) | registers.get(I_EPV5_ALL_L, 0),
         "unit": "kWh",
         "device_class": "energy",
         "state_class": "total_increasing",
         "scale": 0.1,
         "icon": "mdi:solar-power",
         "suggested_display_precision": 1,
         "enabled": True,
         "visible": True,
         "master_only": False,
        "device_group": "Pin mặt trời",
     },
     {
         "name": "Tổng sản lượng PV6",
         "register_type": "calculated",
         "depends_on": [I_EPV6_ALL_L, I_EPV6_ALL_H],
         "extract": lambda registers, entry: (registers.get(I_EPV6_ALL_H, 0) << 16) | registers.get(I_EPV6_ALL_L, 0),
         "unit": "kWh",
         "device_class": "energy",
         "state_class": "total_increasing",
         "scale": 0.1,
         "icon": "mdi:solar-power",
         "suggested_display_precision": 1,
         "enabled": True,
         "visible": True,
         "master_only": False,
        "device_group": "Pin mặt trời",
     },
    {
        "name": "Tổng sản lượng PV",
        "register_type": "calculated",
        "depends_on": [
            I_EPV1_ALL_L, I_EPV1_ALL_H,
            I_EPV2_ALL_L, I_EPV2_ALL_H,
            I_EPV3_ALL_L, I_EPV3_ALL_H,
            I_EPV4_ALL_L, I_EPV4_ALL_H,
            I_EPV5_ALL_L, I_EPV5_ALL_H,
            I_EPV6_ALL_L, I_EPV6_ALL_H,
        ],
        "extract": lambda registers, entry: (
            ((registers.get(I_EPV1_ALL_H, 0) << 16) | registers.get(I_EPV1_ALL_L, 0))
            + ((registers.get(I_EPV2_ALL_H, 0) << 16) | registers.get(I_EPV2_ALL_L, 0))
            + ((registers.get(I_EPV3_ALL_H, 0) << 16) | registers.get(I_EPV3_ALL_L, 0))
            + ((registers.get(I_EPV4_ALL_H, 0) << 16) | registers.get(I_EPV4_ALL_L, 0))
            + ((registers.get(I_EPV5_ALL_H, 0) << 16) | registers.get(I_EPV5_ALL_L, 0))
            + ((registers.get(I_EPV6_ALL_H, 0) << 16) | registers.get(I_EPV6_ALL_L, 0))
        ),
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:solar-power-variant",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin mặt trời",
    },
    {
        "name": "Tổng sản lượng biến tần",
        "register_type": "calculated",
        "depends_on": [I_EINV_ALL_L, I_EINV_ALL_H],
        "extract": lambda registers, entry: (registers.get(I_EINV_ALL_H, 0) << 16) | registers.get(I_EINV_ALL_L, 0),
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:power-plug",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Tổng điện sạc AC",
        "register_type": "calculated",
        "depends_on": [I_EREC_ALL_L, I_EREC_ALL_H],
        "extract": lambda registers, entry: (registers.get(I_EREC_ALL_H, 0) << 16) | registers.get(I_EREC_ALL_L, 0),
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:power-plug",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Tổng điện sạc pin",
        "register_type": "calculated",
        "depends_on": [I_ECHG_ALL_L, I_ECHG_ALL_H],
        "extract": lambda registers, entry: (registers.get(I_ECHG_ALL_H, 0) << 16) | registers.get(I_ECHG_ALL_L, 0),
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:battery-arrow-up-box",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Tổng điện xả pin",
        "register_type": "calculated",
        "depends_on": [I_EDISCHG_ALL_L, I_EDISCHG_ALL_H],
        "extract": lambda registers, entry: (registers.get(I_EDISCHG_ALL_H, 0) << 16) | registers.get(I_EDISCHG_ALL_L, 0),
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:battery-arrow-down-box",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Tổng sản lượng EPS",
        "register_type": "calculated",
        "depends_on": [I_EEPS_ALL_L, I_EEPS_ALL_H],
        "extract": lambda registers, entry: (registers.get(I_EEPS_ALL_H, 0) << 16) | registers.get(I_EEPS_ALL_L, 0),
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:power-plug-off",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "EPS (Off-Grid)",
    },
    {
        "name": "Tổng sản lượng EPS L1N",
        "register_type": "calculated",
        "depends_on": [I_EEPS_L1N_ALL_L, I_EEPS_L1N_ALL_H],
        "extract": lambda registers, entry: (registers.get(I_EEPS_L1N_ALL_H, 0) << 16) | registers.get(I_EEPS_L1N_ALL_L, 0),
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:power-plug-off",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "EPS (Off-Grid)",
    },
    {
        "name": "Tổng sản lượng EPS L2N",
        "register_type": "calculated",
        "depends_on": [I_EEPS_L2N_ALL_L, I_EEPS_L2N_ALL_H],
        "extract": lambda registers, entry: (registers.get(I_EEPS_L2N_ALL_H, 0) << 16) | registers.get(I_EEPS_L2N_ALL_L, 0),
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:power-plug-off",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "EPS (Off-Grid)",
    },
    {
        "name": "Tổng điện phát lưới",
        "register_type": "calculated",
        "depends_on": [I_ETOGRID_ALL_L, I_ETOGRID_ALL_H],
        "extract": lambda registers, entry: (registers.get(I_ETOGRID_ALL_H, 0) << 16) | registers.get(I_ETOGRID_ALL_L, 0),
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:home-export-outline",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Lưới điện",
    },
    {
        "name": "Tổng điện nhập lưới",
        "register_type": "calculated",
        "depends_on": [I_ETOUSER_ALL_L, I_ETOUSER_ALL_H],
        "extract": lambda registers, entry: (registers.get(I_ETOUSER_ALL_H, 0) << 16) | registers.get(I_ETOUSER_ALL_L, 0),
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:home-import-outline",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Lưới điện",
    },
    {
        "name": "Tổng sản lượng máy phát",
        "register_type": "calculated",
        "depends_on": [I_EGEN_ALL_L, I_EGEN_ALL_H],
        "extract": lambda registers, entry: (registers.get(I_EGEN_ALL_H, 0) << 16) | registers.get(I_EGEN_ALL_L, 0),
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:engine",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Máy phát",
    },
    {
        "name": "Tổng điện tiêu thụ tải",
        "register_type": "calculated",
        "depends_on": [I_ELOAD_ALL_L, I_ELOAD_ALL_H],
        "extract": lambda registers, entry: (registers.get(I_ELOAD_ALL_H, 0) << 16) | registers.get(I_ELOAD_ALL_L, 0),
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:home-lightning-bolt",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    # ===========================================================================================
    # THREE-PHASE S/T POWER SENSORS
    # ===========================================================================================
    {
        "name": "Công suất biến tần pha S",
        "register": I_PINV_S,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:power-plug",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Lưới điện",
    },
    {
        "name": "Công suất biến tần pha T",
        "register": I_PINV_T,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:power-plug",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Lưới điện",
    },
    {
        "name": "Công suất chỉnh lưu AC pha S",
        "register": I_PREC_S,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:power-plug",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Lưới điện",
    },
    {
        "name": "Công suất chỉnh lưu AC pha T",
        "register": I_PREC_T,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:power-plug",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Lưới điện",
    },
    {
        "name": "Công suất phát lưới pha S",
        "register": I_PTOGRID_S,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:transmission-tower-export",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Lưới điện",
    },
    {
        "name": "Công suất phát lưới pha T",
        "register": I_PTOGRID_T,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:transmission-tower-export",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Lưới điện",
    },
    {
        "name": "Công suất nhập lưới pha S",
        "register": I_PTOUSER_S,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:transmission-tower-import",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Lưới điện",
    },
    {
        "name": "Công suất nhập lưới pha T",
        "register": I_PTOUSER_T,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:transmission-tower-import",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Lưới điện",
    },
    {
        "name": "Công suất máy phát pha S",
        "register": I_GEN_POWER_S,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:engine",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Máy phát",
    },
    {
        "name": "Công suất máy phát pha T",
        "register": I_GEN_POWER_T,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:engine",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Máy phát",
    },
    {
        "name": "Dòng biến tần pha S",
        "register": I_IINV_RMS_S,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
        "scale": 0.01,
        "icon": "mdi:current-ac",
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Lưới điện",
    },
    {
        "name": "Dòng biến tần pha T",
        "register": I_IINV_RMS_T,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
        "scale": 0.01,
        "icon": "mdi:current-ac",
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Lưới điện",
    },
    {
        "name": "Hệ số công suất pha S",
        "register": I_PF_S,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "%",
        "device_class": "power_factor",
        "state_class": "measurement",
        "scale": 0.001,
        "icon": "mdi:angle-acute",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Lưới điện",
    },
    {
        "name": "Hệ số công suất pha T",
        "register": I_PF_T,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "%",
        "device_class": "power_factor",
        "state_class": "measurement",
        "scale": 0.001,
        "icon": "mdi:angle-acute",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Lưới điện",
    },
    {
        "name": "Công suất tải On-Grid pha S",
        "register": I_ONGRID_LOAD_POWER_S,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:home-lightning-bolt-outline",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Lưới điện",
    },
    {
        "name": "Công suất tải On-Grid pha T",
        "register": I_ONGRID_LOAD_POWER_T,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:home-lightning-bolt-outline",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Lưới điện",
    },

    # ===========================================================================================
    # DIAGNOSTIC SENSORS
    # ===========================================================================================
    {
        "name": "Loại và hãng pin",
        "register": I_BAT_TYPE_AND_BRAND,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1,
        "icon": "mdi:battery-unknown",
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin",
    },
    {
        "name": "Trạng thái cập nhật firmware BMS",
        "register": I_BMS_FW_UPDATE_STATE,
        "register_type": "input",
        "extract": lambda value: value,
        "icon": "mdi:update",
        "enabled": True,
        "visible": True,
        "default": "Chờ",
        "options": {
            0: "Chờ",
            1: "Đang xử lý",
            2: "Thành công",
            3: "Thất bại",
        },
        "master_only": False,
        "device_group": "Pin",
    },
    {
        "name": "Trạng thái công tắc DIP",
        "register": I_SWITCH_STATE,
        "register_type": "input",
        "extract": lambda value: value & 0x1F,
        "unit": "",
        "device_class": None,
        "scale": 1,
        "icon": "mdi:dip-switch",
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Nguyên nhân ngoại lệ 1",
        "register": I_EXCEPTION_REASON_1,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1,
        "icon": "mdi:alert-circle-outline",
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Nguyên nhân ngoại lệ 2",
        "register": I_EXCEPTION_REASON_2,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1,
        "icon": "mdi:alert-circle-outline",
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Lý do tắt sạc/xả",
        "register": I_CHG_DISCHG_DISABLE_REASON,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1,
        "icon": "mdi:battery-off-outline",
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin",
    },
    {
        "name": "Trạng thái kiểm tra tự động",
        "register": I_AUTO_TEST_STATUS,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1,
        "icon": "mdi:test-tube",
        "enabled": True,
        "visible": True,
        "master_only": False,
    },

]

# --- Battery Sensor Types (register range 5000+) ---
# These sensors are created per-battery, using the battery serial as device_group.
BATTERY_SENSOR_TYPES = [
    {
        "name": "Dung lượng",
        "register": B_CAPACITY,
        "register_type": "battery",
        "extract": lambda value: value,
        "unit": "Ah",
        "device_class": None,
        "scale": 1.0,
        "icon": "mdi:car-battery",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Dòng sạc tối đa",
        "register": B_MAX_CHARGE_CURRENT,
        "register_type": "battery",
        "extract": lambda value: value,
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:battery-lock",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Dòng xả tối đa",
        "register": B_MAX_DISCHARGE_CURRENT,
        "register_type": "battery",
        "extract": lambda value: value,
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:battery-lock",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Điện áp",
        "register": B_VOLTAGE,
        "register_type": "battery",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.01,
        "icon": "mdi:car-battery",
        "suggested_display_precision": 2,
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Dòng điện",
        "register": B_CURRENT,
        "register_type": "battery",
        "extract": lambda value: value if value < 32768 else value - 65536,
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:current-dc",
        "suggested_display_precision": 2,
        "enabled": True,
        "visible": True,
    },
    {
        "name": "SOC",
        "register": B_SOH_SOC,
        "register_type": "battery",
        "extract": lambda value: value & 0xFF,
        "unit": "%",
        "device_class": "battery",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:battery-high",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
    },
    {
        "name": "SOH",
        "register": B_SOH_SOC,
        "register_type": "battery",
        "extract": lambda value: (value >> 8) & 0xFF,
        "unit": "%",
        "device_class": None,
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:battery-heart-variant",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Số chu kỳ",
        "register": B_CYCLE_COUNT,
        "register_type": "battery",
        "extract": lambda value: value,
        "unit": "cycles",
        "device_class": None,
        "state_class": "total_increasing",
        "scale": 1.0,
        "icon": "mdi:battery-sync",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Nhiệt độ cell cao nhất",
        "register": B_MAX_CELL_TEMP,
        "register_type": "battery",
        "extract": lambda value: value,
        "unit": "\u00b0C",
        "device_class": "temperature",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:thermometer",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Nhiệt độ cell thấp nhất",
        "register": B_MIN_CELL_TEMP,
        "register_type": "battery",
        "extract": lambda value: value,
        "unit": "\u00b0C",
        "device_class": "temperature",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:thermometer",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Điện áp cell cao nhất",
        "register": B_MAX_CELL_VOLTAGE,
        "register_type": "battery",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.001,
        "icon": "mdi:car-battery",
        "suggested_display_precision": 3,
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Điện áp cell thấp nhất",
        "register": B_MIN_CELL_VOLTAGE,
        "register_type": "battery",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.001,
        "icon": "mdi:car-battery",
        "suggested_display_precision": 3,
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Chênh lệch cell",
        "register_type": "battery_calculated",
        "depends_on": [B_MAX_CELL_VOLTAGE, B_MIN_CELL_VOLTAGE],
        "extract": lambda registers, entry: (
            round((registers.get(B_MAX_CELL_VOLTAGE, 0) - registers.get(B_MIN_CELL_VOLTAGE, 0)) * 0.001, 3)
            if registers.get(B_MAX_CELL_VOLTAGE) is not None and registers.get(B_MIN_CELL_VOLTAGE) is not None
            else None
        ),
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:car-battery",
        "suggested_display_precision": 3,
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Cell nhiệt độ thấp nhất",
        "register": B_TEMP_CELLS,
        "register_type": "battery",
        "extract": lambda value: (value >> 8) & 0xFF,
        "unit": "",
        "device_class": None,
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Cell nhiệt độ cao nhất",
        "register": B_TEMP_CELLS,
        "register_type": "battery",
        "extract": lambda value: value & 0xFF,
        "unit": "",
        "device_class": None,
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Cell điện áp thấp nhất",
        "register": B_VOLTAGE_CELLS,
        "register_type": "battery",
        "extract": lambda value: (value >> 8) & 0xFF,
        "unit": "",
        "device_class": None,
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Cell điện áp cao nhất",
        "register": B_VOLTAGE_CELLS,
        "register_type": "battery",
        "extract": lambda value: value & 0xFF,
        "unit": "",
        "device_class": None,
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Phiên bản firmware",
        "register": B_FIRMWARE,
        "register_type": "battery",
        "extract": lambda value: f"{value >> 8}.{(value & 0xFF):02}",
        "icon": "mdi:information-outline",
        "enabled": True,
        "visible": True,
    },
]
