#
# entity_descriptions/sensor_types.py
#

from ..constants.input_registers import *
from ..constants.hold_registers import H_NO_FULL_CHG_DAY_CONFIG, H_BOOTLOADER_VERSION_AND_FLAG
from ..constants.battery_registers import *
from ..constants.fault_codes import FAULT_CODES
from ..constants.warning_codes import WARNING_CODES
from ..const import CONF_RATED_POWER
from ..utils import decode_bitmask_to_string, get_highest_set_bit

SENSOR_TYPES = [
    # --- Calculated Sensors ---
    {
        "name": "Load Percentage",
        "register_type": "calculated",
        "depends_on": [I_STATE, I_PLOAD, I_PEPS],
        "unit": "%",
        "device_class": "power_factor",
        "state_class": "measurement",
        "icon": "mdi:gauge",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "extract": lambda registers, entry: (
            (
                round((registers.get(I_PEPS, 0) / rated_power) * 100, 2)
                if registers.get(I_STATE) == 64
                else round((registers.get(I_PLOAD, 0) / rated_power) * 100, 2)
            ) if (rated_power := entry.data.get(CONF_RATED_POWER)) and rated_power > 0 else 0
        ),
        "master_only": False,
    },
    {
        "name": "Energy Flow",
        "register_type": "calculated",
        "depends_on": [I_PDISCHARGE, I_PTOUSER, I_PTOUSER_S, I_PTOUSER_T, I_PTOUSER_L1N, I_PTOUSER_L2N, I_PPV1, I_PPV2, I_PPV3, I_PPV4, I_PPV5, I_PPV6],
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:transmission-tower-export",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "extract": lambda registers, entry: (
            lambda battery_discharge, grid_power_total, pv_total: (
                pv_total + grid_power_total - battery_discharge
            )
        )(
            registers.get(I_PDISCHARGE, 0),
            sum(registers.get(grid_reg, 0) for grid_reg in [I_PTOUSER, I_PTOUSER_S, I_PTOUSER_T, I_PTOUSER_L1N, I_PTOUSER_L2N]),
            sum(registers.get(pv_reg, 0) for pv_reg in [I_PPV1, I_PPV2, I_PPV3, I_PPV4, I_PPV5, I_PPV6])
        ),
        "master_only": False,
    },
    {
        "name": "Battery Flow",
        "register_type": "calculated",
        "depends_on": [I_PCHARGE, I_PDISCHARGE],
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:battery-sync",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "extract": lambda registers, entry: (
            registers.get(I_PDISCHARGE, 0) - registers.get(I_PCHARGE, 0)
        ),
        "master_only": False,
        "device_group": "Battery",
    },
    {
        "name": "Grid Flow",
        "register_type": "calculated",
        "depends_on": [I_PTOGRID, I_PTOUSER],
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:transmission-tower",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "extract": lambda registers, entry: (
            registers.get(I_PTOUSER, 0) - registers.get(I_PTOGRID, 0)
        ),
        "master_only": False,
        "device_group": "Grid",
    },

    # --- State Sensors ---
    {
        "name": "Inverter State",
        "register": I_STATE,
        "register_type": "input",
        "extract": lambda value: value,
        "icon": "mdi:state-machine",
        "enabled": True,
        "visible": True,
        "default": "Unknown State",
        "options": {
            0: "Standby",
            1: "Fault",
            2: "Programming / Updating",
            4: "PV Powering Load - Surplus Exporting to Grid",
            8: "PV Powering Load & Charging Battery",
            12: "PV Powering Load, Charging Battery & Exporting to Grid",
            16: "Battery Discharging to Load - Surplus Exporting to Grid",
            17: "Standby",
            20: "PV & Battery Powering Load - Surplus Exporting to Grid",
            32: "Grid Charging Battery",
            40: "Grid & PV Charging Battery",
            64: "Off-Grid: Battery Powering Load",
            96: "Off-Grid: AC Coupled PV Charging Battery",
            128: "Off-Grid: PV Power Unstable (Prohibited)",
            136: "Off-Grid: PV Powering Load & Charging Battery",
            192: "Off-Grid: PV & Battery Powering Load",
        },
        "master_only": False,
    },
    {
        "name": "Inverter State Code",
        "register": I_STATE,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1.0,
        "icon": "mdi:numeric",
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "AC Input Type",
        "register": I_AC_INPUT_TYPE_FLAGS,
        "register_type": "input",
        "extract": lambda value: value & 1, # Extracts Bit 0 from the register
        "icon": "mdi:power-source",
        "enabled": True,
        "visible": True,
        "default": "Grid",
        "options": {
            0: "Grid", # 0 indicates Grid input
            1: "Generator" # 1 indicates Generator input
        },
        "master_only": False,
    },

    # --- Core Status & PV Information ---
    {
        "name": "PV1 Voltage",
        "register": I_VPV1,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "PV",
    },
    {
        "name": "PV1 Power",
        "register": I_PPV1,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "PV",
    },
    {
        "name": "PV1 Current",
        "register_type": "calculated",
        "depends_on": [I_PPV1, I_VPV1],
        "extract": lambda registers, entry: (
            round(registers.get(I_PPV1, 0) / (registers.get(I_VPV1, 0) * 0.1), 2)
            if registers.get(I_VPV1, 0) > 0 else 0
        ),
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 2,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "PV",
    },
    {
        "name": "PV2 Voltage",
        "register": I_VPV2,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "PV",
    },
    {
        "name": "PV2 Power",
        "register": I_PPV2,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "PV",
    },
    {
        "name": "PV2 Current",
        "register_type": "calculated",
        "depends_on": [I_PPV2, I_VPV2],
        "extract": lambda registers, entry: (
            round(registers.get(I_PPV2, 0) / (registers.get(I_VPV2, 0) * 0.1), 2)
            if registers.get(I_VPV2, 0) > 0 else 0
        ),
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 2,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "PV",
    },
    {
        "name": "PV3 Voltage",
        "register": I_VPV3,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "PV",
    },
    {
        "name": "PV3 Power",
        "register": I_PPV3,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "PV",
    },
    {
        "name": "PV3 Current",
        "register_type": "calculated",
        "depends_on": [I_PPV3, I_VPV3],
        "extract": lambda registers, entry: (
            round(registers.get(I_PPV3, 0) / (registers.get(I_VPV3, 0) * 0.1), 2)
            if registers.get(I_VPV3, 0) > 0 else 0
        ),
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 2,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "PV",
    },
    {
        "name": "PV4 Voltage",
        "register": I_VPV4,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "PV",
    },
    {
        "name": "PV4 Power",
        "register": I_PPV4,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "PV",
    },
    {
        "name": "PV4 Current",
        "register_type": "calculated",
        "depends_on": [I_PPV4, I_VPV4],
        "extract": lambda registers, entry: (
            round(registers.get(I_PPV4, 0) / (registers.get(I_VPV4, 0) * 0.1), 2)
            if registers.get(I_VPV4, 0) > 0 else 0
        ),
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 2,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "PV",
    },
    {
        "name": "PV5 Voltage",
        "register": I_VPV5,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "PV",
    },
    {
        "name": "PV5 Power",
        "register": I_PPV5,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "PV",
    },
    {
        "name": "PV5 Current",
        "register_type": "calculated",
        "depends_on": [I_PPV5, I_VPV5],
        "extract": lambda registers, entry: (
            round(registers.get(I_PPV5, 0) / (registers.get(I_VPV5, 0) * 0.1), 2)
            if registers.get(I_VPV5, 0) > 0 else 0
        ),
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 2,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "PV",
    },
    {
        "name": "PV6 Voltage",
        "register": I_VPV6,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "PV",
    },
    {
        "name": "PV6 Power",
        "register": I_PPV6,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "PV",
    },
    {
        "name": "PV6 Current",
        "register_type": "calculated",
        "depends_on": [I_PPV6, I_VPV6],
        "extract": lambda registers, entry: (
            round(registers.get(I_PPV6, 0) / (registers.get(I_VPV6, 0) * 0.1), 2)
            if registers.get(I_VPV6, 0) > 0 else 0
        ),
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 2,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "PV",
    },
    {
        "name": "PV Power",
        "register_type": "calculated",
        "depends_on": [I_PPV1, I_PPV2, I_PPV3, I_PPV4, I_PPV5, I_PPV6],
        "extract": lambda registers, entry: (
            registers.get(I_PPV1, 0) + registers.get(I_PPV2, 0) + registers.get(I_PPV3, 0)
            + registers.get(I_PPV4, 0) + registers.get(I_PPV5, 0) + registers.get(I_PPV6, 0)
        ),
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:solar-power-variant",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "PV",
    },

    # --- Battery Information ---
    {
        "name": "Battery Voltage",
        "register": I_VBAT,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:car-battery",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "Battery SOC",
        "register": I_SOC_SOH,
        "register_type": "input",
        "extract": lambda value: value & 0xFF,
        "unit": "%",
        "device_class": "battery",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:battery-high",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "Battery SOH",
        "register": I_SOC_SOH,
        "register_type": "input",
        "extract": lambda value: (value >> 8) & 0xFF,
        "unit": "%",
        "device_class": None,
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:battery-heart-variant",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "Days since SOC >= 99",
        "register": H_NO_FULL_CHG_DAY_CONFIG,
        "register_type": "hold",
        "extract": lambda value: value & 0xFF,
        "unit": "d",
        "device_class": "duration",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:battery-heart-variant",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "Bootloader Version",
        "register": H_BOOTLOADER_VERSION_AND_FLAG,
        "register_type": "hold",
        "extract": lambda value: value & 0xFF,
        "unit": "",
        "device_class": None,
        "state_class": None,
        "scale": 1.0,
        "icon": "mdi:chip",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Bootloader Update Flag",
        "register": H_BOOTLOADER_VERSION_AND_FLAG,
        "register_type": "hold",
        "extract": lambda value: (value >> 8) & 0xFF,
        "unit": "",
        "device_class": None,
        "state_class": None,
        "scale": 1.0,
        "icon": "mdi:update",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Battery Charge Power",
        "register": I_PCHARGE,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:battery-arrow-up",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Battery",
    },
    {
        "name": "Battery Discharge Power",
        "register": I_PDISCHARGE,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:battery-arrow-down",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Battery",
    },
    {
        "name": "Battery Temperature",
        "register": I_TBAT,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:thermometer",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },

    # --- Grid Information ---
    {
        "name": "Grid Voltage",
        "register": I_VAC_R,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:transmission-tower",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Grid",
    },
    {
        "name": "Grid Voltage S-Phase",
        "register": I_VAC_S,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:transmission-tower",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Grid",
    },
    {
        "name": "Grid Voltage T-Phase",
        "register": I_VAC_T,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:transmission-tower",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Grid",
    },
    {
        "name": "Grid Frequency",
        "register": I_FAC,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "Hz",
        "device_class": "frequency",
        "state_class": "measurement",
        "scale": 0.01,
        "icon": "mdi:sine-wave",
        "suggested_display_precision": 2,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Grid",
    },
    {
        "name": "Grid Voltage L1N",
        "register": I_GRID_VOLT_L1N,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:transmission-tower",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Grid",
    },
    {
        "name": "Grid Voltage L2N",
        "register": I_GRID_VOLT_L2N,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:transmission-tower",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Grid",
    },
    {
        "name": "Inverter Power",
        "register": I_PINV,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:power-plug",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Inverter Power L1N",
        "register": I_PINV_L1N,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:power-plug",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Inverter Power L2N",
        "register": I_PINV_L2N,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:power-plug",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Inverter Current",
        "register": I_IINV_RMS,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
        "scale": 0.01,
        "icon": "mdi:current-ac",
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "AC Charging Rectification Power",
        "register": I_PREC,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:power-plug",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "AC Rectification Power L1N",
        "register": I_PREC_L1N,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:power-plug",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "AC Rectification Power L2N",
        "register": I_PREC_L2N,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:power-plug",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "AC Couple Power",
        "register": I_AC_COUPLE_POWER,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:power-plug",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "AC Coupling",
    },
    {
        "name": "AC Couple Power S-Phase",
        "register": I_AC_COUPLE_POWER_S,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:power-plug",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "AC Coupling",
    },
    {
        "name": "AC Couple Power T-Phase",
        "register": I_AC_COUPLE_POWER_T,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:power-plug",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "AC Coupling",
    },
    {
        "name": "Power Factor",
        "register": I_PF,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "%",
        "device_class": "power_factor",
        "state_class": "measurement",
        "scale": 0.001,
        "icon": "mdi:angle-acute",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
         "name": "Reactive Power",
         "register": I_QINV,
         "register_type": "input",
         "extract": lambda value: value if value < 32768 else value - 65536,
         "unit": "var",
         "device_class": "reactive_power",
         "state_class": "measurement",
         "scale": 1.0,
         "icon": "mdi:flash",
         "suggested_display_precision": 0,
         "enabled": True,
         "visible": True,
         "master_only": False,
     },
    {
        "name": "Power to Grid",
        "register": I_PTOGRID,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:transmission-tower-export",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Grid",
    },
    {
        "name": "Power to Grid L1N",
        "register": I_PTOGRID_L1N,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:transmission-tower-export",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Grid",
    },
    {
        "name": "Power to Grid L2N",
        "register": I_PTOGRID_L2N,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:transmission-tower-export",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Grid",
    },
    {
        "name": "Power from Grid",
        "register": I_PTOUSER,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:transmission-tower-import",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Grid",
    },
    {
        "name": "Power from Grid L1N",
        "register": I_PTOUSER_L1N,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:transmission-tower-import",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Grid",
    },
    {
        "name": "Power from Grid L2N",
        "register": I_PTOUSER_L2N,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:transmission-tower-import",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Grid",
    },
    {
        "name": "Load Power",
        "register": I_PLOAD,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:home-lightning-bolt",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "On-Grid Load Power",
        "register": I_ONGRID_LOAD_POWER,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:home-lightning-bolt-outline",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Grid",
    },
    {
        "name": "Smart Load Power",
        "register": I_SMART_LOAD_POWER,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:home-lightning-bolt-outline",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },

    # --- EPS (Off-Grid) Information ---
    {
        "name": "EPS Voltage",
        "register": I_VEPS_R,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:power-plug-off",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "EPS",
    },
    {
        "name": "EPS Voltage L1N",
        "register": I_EPS_VOLT_L1N,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:power-plug-off",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "EPS",
    },
    {
        "name": "EPS Voltage L2N",
        "register": I_EPS_VOLT_L2N,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:power-plug-off",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "EPS",
    },
    {
        "name": "EPS Voltage S-Phase",
        "register": I_VEPS_S,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:power-plug-off",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "EPS",
    },
    {
        "name": "EPS Voltage T-Phase",
        "register": I_VEPS_T,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:power-plug-off",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "EPS",
    },
    {
        "name": "EPS Frequency",
        "register": I_FEPS,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "Hz",
        "device_class": "frequency",
        "state_class": "measurement",
        "scale": 0.01,
        "icon": "mdi:sine-wave",
        "suggested_display_precision": 2,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "EPS",
    },
    {
        "name": "EPS Power",
        "register": I_PEPS,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:power-plug-off",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "EPS",
    },
    {
        "name": "EPS Power L1N",
        "register": I_PEPS_L1N,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:power-plug-off",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "EPS",
    },
    {
        "name": "EPS Power L2N",
        "register": I_PEPS_L2N,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:power-plug-off",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "EPS",
    },
    {
        "name": "EPS Apparent Power",
        "register": I_SEPS,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "VA",
        "device_class": "apparent_power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:power-plug-off",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "EPS",
    },
    {
        "name": "EPS Apparent Power L1N",
        "register": I_SEPS_L1N,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "VA",
        "device_class": "apparent_power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:power-plug-off",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "EPS",
    },
    {
        "name": "EPS Apparent Power L2N",
        "register": I_SEPS_L2N,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "VA",
        "device_class": "apparent_power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:power-plug-off",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "EPS",
    },

    # --- Daily Energy ---
    {
        "name": "PV1 Energy Today",
        "register": I_EPV1_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "PV",
    },
    {
        "name": "PV2 Energy Today",
        "register": I_EPV2_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "PV",
    },
    {
        "name": "PV3 Energy Today",
        "register": I_EPV3_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "PV",
    },
    {
        "name": "PV4 Energy Today",
        "register": I_EPV4_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "PV",
    },
    {
        "name": "PV5 Energy Today",
        "register": I_EPV5_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "PV",
    },
    {
        "name": "PV6 Energy Today",
        "register": I_EPV6_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "PV",
    },
    {
        "name": "PV Energy Today",
        "register_type": "calculated",
        "depends_on": [I_EPV1_DAY, I_EPV2_DAY, I_EPV3_DAY, I_EPV4_DAY, I_EPV5_DAY, I_EPV6_DAY],
        "extract": lambda registers, entry: (
            registers.get(I_EPV1_DAY, 0) + registers.get(I_EPV2_DAY, 0) + registers.get(I_EPV3_DAY, 0)
            + registers.get(I_EPV4_DAY, 0) + registers.get(I_EPV5_DAY, 0) + registers.get(I_EPV6_DAY, 0)
        ),
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:solar-power-variant",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "PV",
    },
    {
        "name": "Inverter Energy Today",
        "register": I_EINV_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:power-plug",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "AC Charge Energy Today",
        "register": I_EREC_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:power-plug",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Charge Energy Today",
        "register": I_ECHG_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:battery-arrow-up-box",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Discharge Energy Today",
        "register": I_EDISCHG_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:battery-arrow-down-box",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "EPS Energy Today",
        "register": I_EEPS_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:power-plug-off",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "EPS",
    },
    {
        "name": "EPS Energy Today L1N",
        "register": I_EEPS_L1N_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:power-plug-off",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "EPS",
    },
    {
        "name": "EPS Energy Today L2N",
        "register": I_EEPS_L2N_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:power-plug-off",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "EPS",
    },
    {
        "name": "Energy to Grid Today",
        "register": I_ETOGRID_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:home-export-outline",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Grid",
    },
    {
        "name": "Energy from Grid Today",
        "register": I_ETOUSER_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:home-import-outline",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Grid",
    },
    {
        "name": "Generator Energy Today",
        "register": I_EGEN_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:engine",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Generator",
    },
    {
        "name": "Load Consumption Today",
        "register": I_ELOAD_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:home-lightning-bolt",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },

    # --- System, Temperature & Generator ---
    {
        "name": "Internal Temperature",
        "register": I_TINNER,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:thermometer",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Internal Temperature 2",
        "register": I_TEMP_NTC_FOR_INDC,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:thermometer",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Radiator Temperature",
        "register": I_TRADIATOR1,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:fan",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Radiator Temperature 2",
        "register": I_TRADIATOR2,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:fan",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Radiator Temperature 3",
        "register": I_TEMP_NTC_FOR_DCDCL,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:fan",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Radiator Temperature 4",
        "register": I_TEMP_NTC_FOR_DCDCH,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:fan",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Generator Voltage",
        "register": I_GEN_VOLT,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:engine",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Generator",
    },
    {
        "name": "Generator Voltage L1N",
        "register": I_GEN_VOLT_L1N,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:engine",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Generator",
    },
    {
        "name": "Generator Voltage L2N",
        "register": I_GEN_VOLT_L2N,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:engine",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Generator",
    },
    {
        "name": "Generator Frequency",
        "register": I_GEN_FREQ,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "Hz",
        "device_class": "frequency",
        "state_class": "measurement",
        "scale": 0.01,
        "icon": "mdi:engine",
        "suggested_display_precision": 2,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Generator",
    },
    {
        "name": "Generator Power",
        "register": I_GEN_POWER,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:engine",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Generator",
    },
    {
        "name": "Remaining One-Click Charge Time",
        "register": I_REMAINING_CHARGE_TIME,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "min",
        "device_class": "duration",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:timer-sand",
        "enabled": True,
        "visible": True,
        "master_only": False,
    },

    # --- System & Bus Voltages ---
    {
        "name": "Bus 1 Voltage",
        "register": I_VBUS1,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1, # Unit is 0.1V
        "icon": "mdi:bus-school",
        "suggested_display_precision": 1,
        "enabled": True,  # Typically for diagnostics
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Bus 2 Voltage",
        "register": I_VBUS2,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1, # Unit is 0.1V
        "icon": "mdi:bus-school",
        "suggested_display_precision": 1,
        "enabled": True, # Typically for diagnostics
        "visible": True, 
        "master_only": False,
    },
    {
        "name": "Half Bus Voltage",
        "register": I_VBUS_P,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1, # Unit is 0.1V
        "icon": "mdi:bus-school",
        "suggested_display_precision": 1,
        "enabled": True, # Typically for diagnostics
        "visible": True,
        "master_only": False,
    },

    # --- BMS Information ---
    {
        "name": "BMS Max Charge Current",
        "register": I_BMS_MAX_CHG_CURR,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:battery-lock",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "BMS Max Discharge Current",
        "register": I_BMS_MAX_DISCHG_CURR,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:battery-lock",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "BMS Charge Voltage Reference",
        "register": I_BMS_CHARGE_VOLT_REF,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:battery-sync",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "BMS Discharge Cut-off Voltage",
        "register": I_BMS_DISCHG_CUT_VOLT,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:battery-sync",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "Battery Parallel Number",
        "register": I_BAT_PARALLEL_NUM,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1.0,
        "icon": "mdi:battery-sync",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "Battery Capacity",
        "register": I_BAT_CAPACITY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "Ah",
        "device_class": None,
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:car-battery",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "BMS Battery Current",
        "register": I_BMS_BAT_CURRENT,
        "register_type": "input",
        "extract": lambda value: value if value < 32768 else value - 65536,
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:current-dc",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "BMS Fault Code",
        "register": I_BMS_FAULT_CODE,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1.0,
        "icon": "mdi:alert-circle-outline",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "BMS Warning Code",
        "register": I_BMS_WARNING_CODE,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1.0,
        "icon": "mdi:alert-outline",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "BMS Max Cell Voltage",
        "register": I_BMS_MAX_CELL_VOLT,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.001,
        "icon": "mdi:battery-positive",
        "suggested_display_precision": 3,
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "BMS Min Cell Voltage",
        "register": I_BMS_MIN_CELL_VOLT,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.001,
        "icon": "mdi:battery-negative",
        "suggested_display_precision": 3,
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "BMS Cell Difference",
        "register_type": "calculated",
        "depends_on": [I_BMS_MIN_CELL_VOLT, I_BMS_MAX_CELL_VOLT],
        "extract": lambda registers, entry: (
            round((registers.get(I_BMS_MAX_CELL_VOLT) - registers.get(I_BMS_MIN_CELL_VOLT)) / 1000.0, 3)
            if registers.get(I_BMS_MAX_CELL_VOLT) is not None and registers.get(I_BMS_MIN_CELL_VOLT) is not None
            else None
        ),
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:car-battery",
        "suggested_display_precision": 3,
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "BMS Max Cell Temperature",
        "register": I_BMS_MAX_CELL_TEMP,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:thermometer-chevron-up",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "BMS Min Cell Temperature",
        "register": I_BMS_MIN_CELL_TEMP,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:thermometer-chevron-down",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "BMS Cycle Count",
        "register": I_BMS_CYCLE_COUNT,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "cycles",
        "device_class": None,
        "state_class": "total_increasing",
        "scale": 1.0,
        "icon": "mdi:battery-sync",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "BMS Battery Status 0",
        "register": I_BMS_BAT_STATUS_0,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1.0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Battery",
    },
    {
        "name": "BMS Battery Status 1",
        "register": I_BMS_BAT_STATUS_1,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1.0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Battery",
    },
    {
        "name": "BMS Battery Status 2",
        "register": I_BMS_BAT_STATUS_2,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1.0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Battery",
    },
    {
        "name": "BMS Battery Status 3",
        "register": I_BMS_BAT_STATUS_3,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1.0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Battery",
    },
    {
        "name": "BMS Battery Status 4",
        "register": I_BMS_BAT_STATUS_4,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1.0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Battery",
    },
    {
        "name": "BMS Battery Status 5",
        "register": I_BMS_BAT_STATUS_5,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1.0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Battery",
    },
    {
        "name": "BMS Battery Status 6",
        "register": I_BMS_BAT_STATUS_6,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1.0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Battery",
    },
    {
        "name": "BMS Battery Status 7",
        "register": I_BMS_BAT_STATUS_7,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1.0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Battery",
    },
    {
        "name": "BMS Battery Status 8",
        "register": I_BMS_BAT_STATUS_8,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1.0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Battery",
    },
    {
        "name": "BMS Battery Status 9",
        "register": I_BMS_BAT_STATUS_9,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1.0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Battery",
    },
    {
        "name": "BMS Battery Status Aggregated",
        "register": I_BMS_BAT_STATUS_INV,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1.0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Battery",
    },
    {
         "name": "Inverter Battery Voltage Sample",
         "register": I_INV_BAT_VOLT_SAMPLE,
         "register_type": "input",
         "extract": lambda value: value,
         "unit": "V",
         "device_class": "voltage",
         "state_class": "measurement",
         "scale": 0.1,
         "icon": "mdi:battery-scan",
         "suggested_display_precision": 1,
         "enabled": True,
         "visible": True,
         "master_only": True,
        "device_group": "Battery",
     },

    # --- Faults & Warnings ---
    {
        "name": "Internal Fault Code",
        "register": I_INTERNAL_FAULT,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1.0,
        "icon": "mdi:alert-box-outline",
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Active Fault (Code)",
        "register_type": "calculated",
        "depends_on": [I_FAULT_CODE_L, I_FAULT_CODE_H],
        "icon": "mdi:numeric",
        "enabled": True,
        "visible": True,
        "extract": lambda registers, entry: get_highest_set_bit(
            (registers.get(I_FAULT_CODE_H, 0) << 16) | registers.get(I_FAULT_CODE_L, 0)
        ),
        "master_only": False,
    },
    {
        "name": "Active Fault (Text)",
        "register_type": "calculated",
        "depends_on": [I_FAULT_CODE_L, I_FAULT_CODE_H],
        "icon": "mdi:alert-circle-outline",
        "enabled": True,
        "visible": True,
        "extract": lambda registers, entry: decode_bitmask_to_string(
            (registers.get(I_FAULT_CODE_H, 0) << 16) | registers.get(I_FAULT_CODE_L, 0),
            FAULT_CODES,
            "No Faults"
        ),
        "master_only": False,
    },
    {
        "name": "Active Warning (Code)",
        "register_type": "calculated",
        "depends_on": [I_WARNING_CODE_L, I_WARNING_CODE_H],
        "icon": "mdi:numeric",
        "enabled": True,
        "visible": True,
        "extract": lambda registers, entry: get_highest_set_bit(
            (registers.get(I_WARNING_CODE_H, 0) << 16) | registers.get(I_WARNING_CODE_L, 0)
        ),
        "master_only": False,
    },
    {
        "name": "Active Warning (Text)",
        "register_type": "calculated",
        "depends_on": [I_WARNING_CODE_L, I_WARNING_CODE_H],
        "icon": "mdi:alert-outline",
        "enabled": True,
        "visible": True,
        "extract": lambda registers, entry: decode_bitmask_to_string(
            (registers.get(I_WARNING_CODE_H, 0) << 16) | registers.get(I_WARNING_CODE_L, 0),
            WARNING_CODES,
            "No Warnings"
        ),
        "master_only": False,
    },

    # --- Parallel Status ---
    {
        "name": "Parallel Role",
        "register": I_MASTER_SLAVE_PARALLEL_STATUS,
        "register_type": "input",
        "extract": lambda value: value & 3,
        "icon": "mdi:vector-link",
        "enabled": True,
        "visible": True,
        "options": {
            1: "Master",
            2: "Slave",
            3: "Parallel On"
        },
        "default": "Standalone",
        "master_only": False,
    },
    {
        "name": "Parallel Phase",
        "register": I_MASTER_SLAVE_PARALLEL_STATUS,
        "register_type": "input",
        "extract": lambda value: (value >> 2) & 3,
        "icon": "mdi:chart-timeline-variant",
        "enabled": True,
        "visible": True,
        "options": {
            1: "R Phase",
            2: "S Phase",
            3: "T Phase"
        },
        "default": "Unknown",
        "master_only": False,
        "device_group": "Grid",
    },
    {
        "name": "Phase Sequence",
        "register": I_MASTER_SLAVE_PARALLEL_STATUS,
        "register_type": "input",
        "extract": lambda value: (value >> 4) & 3,
        "icon": "mdi:rotate-3d-variant",
        "enabled": True,
        "visible": True,
        "options": {
            0: "Positive",
            1: "Negative"
        },
        "default": "Unknown",
        "master_only": False,
        "device_group": "Grid",
    },
    {
        "name": "Parallel Inverter Number",
        "register": I_MASTER_SLAVE_PARALLEL_STATUS,
        "register_type": "input",
        "extract": lambda value: (value >> 8) & 511,
        "unit": "",
        "device_class": None,
        "scale": 1,
        "icon": "mdi:counter",
        "enabled": True,
        "visible": True,
        "master_only": False,
    },

    # --- Cumulative (Lifetime) Totals ---
    {
        "name": "Total Running Time",
        "register_type": "calculated",
        "depends_on": [I_RUNNING_TIME_L, I_RUNNING_TIME_H],
        "extract": lambda registers, entry: (registers.get(I_RUNNING_TIME_H, 0) << 16) | registers.get(I_RUNNING_TIME_L, 0),
        "unit": "s",
        "device_class": "duration",
        "state_class": "total_increasing",
        "scale": 1.0,
        "icon": "mdi:timer",
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "PV1 Energy Total",
        "register_type": "calculated",
        "depends_on": [I_EPV1_ALL_L, I_EPV1_ALL_H],
        "extract": lambda registers, entry: (registers.get(I_EPV1_ALL_H, 0) << 16) | registers.get(I_EPV1_ALL_L, 0),
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "PV",
    },
    {
        "name": "PV2 Energy Total",
        "register_type": "calculated",
        "depends_on": [I_EPV2_ALL_L, I_EPV2_ALL_H],
        "extract": lambda registers, entry: (registers.get(I_EPV2_ALL_H, 0) << 16) | registers.get(I_EPV2_ALL_L, 0),
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "PV",
    },
    {
        "name": "PV3 Energy Total",
        "register_type": "calculated",
        "depends_on": [I_EPV3_ALL_L, I_EPV3_ALL_H],
        "extract": lambda registers, entry: (registers.get(I_EPV3_ALL_H, 0) << 16) | registers.get(I_EPV3_ALL_L, 0),
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "PV",
    },
    {
        "name": "PV4 Energy Total",
        "register_type": "calculated",
        "depends_on": [I_EPV4_ALL_L, I_EPV4_ALL_H],
        "extract": lambda registers, entry: (registers.get(I_EPV4_ALL_H, 0) << 16) | registers.get(I_EPV4_ALL_L, 0),
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:solar-power",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "PV",
    },
    {
         "name": "PV5 Energy Total",
         "register_type": "calculated",
         "depends_on": [I_EPV5_ALL_L, I_EPV5_ALL_H],
         "extract": lambda registers, entry: (registers.get(I_EPV5_ALL_H, 0) << 16) | registers.get(I_EPV5_ALL_L, 0),
         "unit": "kWh",
         "device_class": "energy",
         "state_class": "total_increasing",
         "scale": 0.1,
         "icon": "mdi:solar-power",
         "suggested_display_precision": 1,
         "enabled": True,
         "visible": True,
         "master_only": False,
        "device_group": "PV",
     },
     {
         "name": "PV6 Energy Total",
         "register_type": "calculated",
         "depends_on": [I_EPV6_ALL_L, I_EPV6_ALL_H],
         "extract": lambda registers, entry: (registers.get(I_EPV6_ALL_H, 0) << 16) | registers.get(I_EPV6_ALL_L, 0),
         "unit": "kWh",
         "device_class": "energy",
         "state_class": "total_increasing",
         "scale": 0.1,
         "icon": "mdi:solar-power",
         "suggested_display_precision": 1,
         "enabled": True,
         "visible": True,
         "master_only": False,
        "device_group": "PV",
     },
    {
        "name": "PV Energy Total",
        "register_type": "calculated",
        "depends_on": [
            I_EPV1_ALL_L, I_EPV1_ALL_H,
            I_EPV2_ALL_L, I_EPV2_ALL_H,
            I_EPV3_ALL_L, I_EPV3_ALL_H,
            I_EPV4_ALL_L, I_EPV4_ALL_H,
            I_EPV5_ALL_L, I_EPV5_ALL_H,
            I_EPV6_ALL_L, I_EPV6_ALL_H,
        ],
        "extract": lambda registers, entry: (
            ((registers.get(I_EPV1_ALL_H, 0) << 16) | registers.get(I_EPV1_ALL_L, 0))
            + ((registers.get(I_EPV2_ALL_H, 0) << 16) | registers.get(I_EPV2_ALL_L, 0))
            + ((registers.get(I_EPV3_ALL_H, 0) << 16) | registers.get(I_EPV3_ALL_L, 0))
            + ((registers.get(I_EPV4_ALL_H, 0) << 16) | registers.get(I_EPV4_ALL_L, 0))
            + ((registers.get(I_EPV5_ALL_H, 0) << 16) | registers.get(I_EPV5_ALL_L, 0))
            + ((registers.get(I_EPV6_ALL_H, 0) << 16) | registers.get(I_EPV6_ALL_L, 0))
        ),
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:solar-power-variant",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "PV",
    },
    {
        "name": "Inverter Energy Total",
        "register_type": "calculated",
        "depends_on": [I_EINV_ALL_L, I_EINV_ALL_H],
        "extract": lambda registers, entry: (registers.get(I_EINV_ALL_H, 0) << 16) | registers.get(I_EINV_ALL_L, 0),
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:power-plug",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "AC Charge Energy Total",
        "register_type": "calculated",
        "depends_on": [I_EREC_ALL_L, I_EREC_ALL_H],
        "extract": lambda registers, entry: (registers.get(I_EREC_ALL_H, 0) << 16) | registers.get(I_EREC_ALL_L, 0),
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:power-plug",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Charge Energy Total",
        "register_type": "calculated",
        "depends_on": [I_ECHG_ALL_L, I_ECHG_ALL_H],
        "extract": lambda registers, entry: (registers.get(I_ECHG_ALL_H, 0) << 16) | registers.get(I_ECHG_ALL_L, 0),
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:battery-arrow-up-box",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Discharge Energy Total",
        "register_type": "calculated",
        "depends_on": [I_EDISCHG_ALL_L, I_EDISCHG_ALL_H],
        "extract": lambda registers, entry: (registers.get(I_EDISCHG_ALL_H, 0) << 16) | registers.get(I_EDISCHG_ALL_L, 0),
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:battery-arrow-down-box",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "EPS Energy Total",
        "register_type": "calculated",
        "depends_on": [I_EEPS_ALL_L, I_EEPS_ALL_H],
        "extract": lambda registers, entry: (registers.get(I_EEPS_ALL_H, 0) << 16) | registers.get(I_EEPS_ALL_L, 0),
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:power-plug-off",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "EPS",
    },
    {
        "name": "EPS Energy Total L1N",
        "register_type": "calculated",
        "depends_on": [I_EEPS_L1N_ALL_L, I_EEPS_L1N_ALL_H],
        "extract": lambda registers, entry: (registers.get(I_EEPS_L1N_ALL_H, 0) << 16) | registers.get(I_EEPS_L1N_ALL_L, 0),
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:power-plug-off",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "EPS",
    },
    {
        "name": "EPS Energy Total L2N",
        "register_type": "calculated",
        "depends_on": [I_EEPS_L2N_ALL_L, I_EEPS_L2N_ALL_H],
        "extract": lambda registers, entry: (registers.get(I_EEPS_L2N_ALL_H, 0) << 16) | registers.get(I_EEPS_L2N_ALL_L, 0),
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:power-plug-off",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "EPS",
    },
    {
        "name": "Energy to Grid Total",
        "register_type": "calculated",
        "depends_on": [I_ETOGRID_ALL_L, I_ETOGRID_ALL_H],
        "extract": lambda registers, entry: (registers.get(I_ETOGRID_ALL_H, 0) << 16) | registers.get(I_ETOGRID_ALL_L, 0),
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:home-export-outline",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Grid",
    },
    {
        "name": "Energy from Grid Total",
        "register_type": "calculated",
        "depends_on": [I_ETOUSER_ALL_L, I_ETOUSER_ALL_H],
        "extract": lambda registers, entry: (registers.get(I_ETOUSER_ALL_H, 0) << 16) | registers.get(I_ETOUSER_ALL_L, 0),
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:home-import-outline",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Grid",
    },
    {
        "name": "Generator Energy Total",
        "register_type": "calculated",
        "depends_on": [I_EGEN_ALL_L, I_EGEN_ALL_H],
        "extract": lambda registers, entry: (registers.get(I_EGEN_ALL_H, 0) << 16) | registers.get(I_EGEN_ALL_L, 0),
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:engine",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Generator",
    },
    {
        "name": "Load Consumption Total",
        "register_type": "calculated",
        "depends_on": [I_ELOAD_ALL_L, I_ELOAD_ALL_H],
        "extract": lambda registers, entry: (registers.get(I_ELOAD_ALL_H, 0) << 16) | registers.get(I_ELOAD_ALL_L, 0),
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "scale": 0.1,
        "icon": "mdi:home-lightning-bolt",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    # ===========================================================================================
    # THREE-PHASE S/T POWER SENSORS
    # ===========================================================================================
    {
        "name": "Inverter Power S-Phase",
        "register": I_PINV_S,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:power-plug",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Grid",
    },
    {
        "name": "Inverter Power T-Phase",
        "register": I_PINV_T,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:power-plug",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Grid",
    },
    {
        "name": "AC Rectification Power S-Phase",
        "register": I_PREC_S,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:power-plug",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Grid",
    },
    {
        "name": "AC Rectification Power T-Phase",
        "register": I_PREC_T,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:power-plug",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Grid",
    },
    {
        "name": "Power to Grid S-Phase",
        "register": I_PTOGRID_S,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:transmission-tower-export",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Grid",
    },
    {
        "name": "Power to Grid T-Phase",
        "register": I_PTOGRID_T,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:transmission-tower-export",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Grid",
    },
    {
        "name": "Power from Grid S-Phase",
        "register": I_PTOUSER_S,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:transmission-tower-import",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Grid",
    },
    {
        "name": "Power from Grid T-Phase",
        "register": I_PTOUSER_T,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:transmission-tower-import",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Grid",
    },
    {
        "name": "Generator Power S-Phase",
        "register": I_GEN_POWER_S,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:engine",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Generator",
    },
    {
        "name": "Generator Power T-Phase",
        "register": I_GEN_POWER_T,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:engine",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Generator",
    },
    {
        "name": "Inverter Current S-Phase",
        "register": I_IINV_RMS_S,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
        "scale": 0.01,
        "icon": "mdi:current-ac",
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Grid",
    },
    {
        "name": "Inverter Current T-Phase",
        "register": I_IINV_RMS_T,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
        "scale": 0.01,
        "icon": "mdi:current-ac",
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Grid",
    },
    {
        "name": "Power Factor S-Phase",
        "register": I_PF_S,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "%",
        "device_class": "power_factor",
        "state_class": "measurement",
        "scale": 0.001,
        "icon": "mdi:angle-acute",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Grid",
    },
    {
        "name": "Power Factor T-Phase",
        "register": I_PF_T,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "%",
        "device_class": "power_factor",
        "state_class": "measurement",
        "scale": 0.001,
        "icon": "mdi:angle-acute",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Grid",
    },
    {
        "name": "On-Grid Load Power S-Phase",
        "register": I_ONGRID_LOAD_POWER_S,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:home-lightning-bolt-outline",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Grid",
    },
    {
        "name": "On-Grid Load Power T-Phase",
        "register": I_ONGRID_LOAD_POWER_T,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:home-lightning-bolt-outline",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Grid",
    },

    # ===========================================================================================
    # DIAGNOSTIC SENSORS
    # ===========================================================================================
    {
        "name": "Battery Type and Brand",
        "register": I_BAT_TYPE_AND_BRAND,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1,
        "icon": "mdi:battery-unknown",
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Battery",
    },
    {
        "name": "BMS Firmware Update State",
        "register": I_BMS_FW_UPDATE_STATE,
        "register_type": "input",
        "extract": lambda value: value,
        "icon": "mdi:update",
        "enabled": True,
        "visible": True,
        "default": "Idle",
        "options": {
            0: "Idle",
            1: "In Process",
            2: "Success",
            3: "Failed",
        },
        "master_only": False,
        "device_group": "Battery",
    },
    {
        "name": "DIP Switch State",
        "register": I_SWITCH_STATE,
        "register_type": "input",
        "extract": lambda value: value & 0x1F,
        "unit": "",
        "device_class": None,
        "scale": 1,
        "icon": "mdi:dip-switch",
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Exception Reason 1",
        "register": I_EXCEPTION_REASON_1,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1,
        "icon": "mdi:alert-circle-outline",
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Exception Reason 2",
        "register": I_EXCEPTION_REASON_2,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1,
        "icon": "mdi:alert-circle-outline",
        "enabled": True,
        "visible": True,
        "master_only": False,
    },
    {
        "name": "Charge Discharge Disable Reason",
        "register": I_CHG_DISCHG_DISABLE_REASON,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1,
        "icon": "mdi:battery-off-outline",
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Battery",
    },
    {
        "name": "Auto Test Status",
        "register": I_AUTO_TEST_STATUS,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1,
        "icon": "mdi:test-tube",
        "enabled": True,
        "visible": True,
        "master_only": False,
    },

]

# --- Battery Sensor Types (register range 5000+) ---
# These sensors are created per-battery, using the battery serial as device_group.
BATTERY_SENSOR_TYPES = [
    {
        "name": "Capacity",
        "register": B_CAPACITY,
        "register_type": "battery",
        "extract": lambda value: value,
        "unit": "Ah",
        "device_class": None,
        "scale": 1.0,
        "icon": "mdi:car-battery",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Max Charge Current",
        "register": B_MAX_CHARGE_CURRENT,
        "register_type": "battery",
        "extract": lambda value: value,
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:battery-lock",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Max Discharge Current",
        "register": B_MAX_DISCHARGE_CURRENT,
        "register_type": "battery",
        "extract": lambda value: value,
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:battery-lock",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Voltage",
        "register": B_VOLTAGE,
        "register_type": "battery",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.01,
        "icon": "mdi:car-battery",
        "suggested_display_precision": 2,
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Current",
        "register": B_CURRENT,
        "register_type": "battery",
        "extract": lambda value: value if value < 32768 else value - 65536,
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:current-dc",
        "suggested_display_precision": 2,
        "enabled": True,
        "visible": True,
    },
    {
        "name": "SOC",
        "register": B_SOH_SOC,
        "register_type": "battery",
        "extract": lambda value: value & 0xFF,
        "unit": "%",
        "device_class": "battery",
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:battery-high",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
    },
    {
        "name": "SOH",
        "register": B_SOH_SOC,
        "register_type": "battery",
        "extract": lambda value: (value >> 8) & 0xFF,
        "unit": "%",
        "device_class": None,
        "state_class": "measurement",
        "scale": 1.0,
        "icon": "mdi:battery-heart-variant",
        "suggested_display_precision": 0,
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Cycle Count",
        "register": B_CYCLE_COUNT,
        "register_type": "battery",
        "extract": lambda value: value,
        "unit": "cycles",
        "device_class": None,
        "state_class": "total_increasing",
        "scale": 1.0,
        "icon": "mdi:battery-sync",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Max Cell Temperature",
        "register": B_MAX_CELL_TEMP,
        "register_type": "battery",
        "extract": lambda value: value,
        "unit": "\u00b0C",
        "device_class": "temperature",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:thermometer",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Min Cell Temperature",
        "register": B_MIN_CELL_TEMP,
        "register_type": "battery",
        "extract": lambda value: value,
        "unit": "\u00b0C",
        "device_class": "temperature",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:thermometer",
        "suggested_display_precision": 1,
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Max Cell Voltage",
        "register": B_MAX_CELL_VOLTAGE,
        "register_type": "battery",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.001,
        "icon": "mdi:car-battery",
        "suggested_display_precision": 3,
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Min Cell Voltage",
        "register": B_MIN_CELL_VOLTAGE,
        "register_type": "battery",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 0.001,
        "icon": "mdi:car-battery",
        "suggested_display_precision": 3,
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Cell Difference",
        "register_type": "battery_calculated",
        "depends_on": [B_MAX_CELL_VOLTAGE, B_MIN_CELL_VOLTAGE],
        "extract": lambda registers, entry: (
            round((registers.get(B_MAX_CELL_VOLTAGE, 0) - registers.get(B_MIN_CELL_VOLTAGE, 0)) * 0.001, 3)
            if registers.get(B_MAX_CELL_VOLTAGE) is not None and registers.get(B_MIN_CELL_VOLTAGE) is not None
            else None
        ),
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:car-battery",
        "suggested_display_precision": 3,
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Cell with Min Temp",
        "register": B_TEMP_CELLS,
        "register_type": "battery",
        "extract": lambda value: (value >> 8) & 0xFF,
        "unit": "",
        "device_class": None,
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Cell with Max Temp",
        "register": B_TEMP_CELLS,
        "register_type": "battery",
        "extract": lambda value: value & 0xFF,
        "unit": "",
        "device_class": None,
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Cell with Min Voltage",
        "register": B_VOLTAGE_CELLS,
        "register_type": "battery",
        "extract": lambda value: (value >> 8) & 0xFF,
        "unit": "",
        "device_class": None,
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Cell with Max Voltage",
        "register": B_VOLTAGE_CELLS,
        "register_type": "battery",
        "extract": lambda value: value & 0xFF,
        "unit": "",
        "device_class": None,
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Firmware Version",
        "register": B_FIRMWARE,
        "register_type": "battery",
        "extract": lambda value: f"{value >> 8}.{(value & 0xFF):02}",
        "icon": "mdi:information-outline",
        "enabled": True,
        "visible": True,
    },
]
