from ..constants.hold_registers import *
from ..utils import get_bits, set_bits

SWITCH_TYPES = [
    # Register 21: H_FUNCTION_ENABLE_1
    {
        "name": "Dự phòng điện",
        "register": H_FUNCTION_ENABLE_1, # 21
        "register_type": "hold",
        "extract": lambda reg: get_bits(reg, 0, 1),
        "compose": lambda orig, value: set_bits(orig, 0, 1, value),
        "icon": "mdi:power-plug-off",
        "device_class": "switch",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lưới điện",
    },
    {
        "name": "Giảm tải khi tần số cao",
        "register": H_FUNCTION_ENABLE_1, # 21
        "register_type": "hold",
        "extract": lambda reg: get_bits(reg, 1, 1),
        "compose": lambda orig, value: set_bits(orig, 1, 1, value),
        "icon": "mdi:chart-bell-curve",
        "device_class": "switch",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lưới điện",
    },
    {
        "name": "DRMS",
        "register": H_FUNCTION_ENABLE_1, # 21
        "register_type": "hold",
        "extract": lambda reg: get_bits(reg, 2, 1),
        "compose": lambda orig, value: set_bits(orig, 2, 1, value),
        "icon": "mdi:grid",
        "device_class": "switch",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lưới điện",
    },
    {
        "name": "Sạc từ điện lưới (AC)",
        "register": H_FUNCTION_ENABLE_1, # 21
        "register_type": "hold",
        "extract": lambda reg: get_bits(reg, 7, 1),
        "compose": lambda orig, value: set_bits(orig, 7, 1, value),
        "icon": "mdi:battery-charging",
        "device_class": "switch",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Chuyển EPS không gián đoạn",
        "register": H_FUNCTION_ENABLE_1, # 21
        "register_type": "hold",
        "extract": lambda reg: get_bits(reg, 8, 1),
        "compose": lambda orig, value: set_bits(orig, 8, 1, value),
        "icon": "mdi:lightning-bolt-circle",
        "device_class": "switch",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Xả cưỡng bức",
        "register": H_FUNCTION_ENABLE_1, # 21
        "register_type": "hold",
        "extract": lambda reg: get_bits(reg, 10, 1),
        "compose": lambda orig, value: set_bits(orig, 10, 1, value),
        "icon": "mdi:battery-arrow-down",
        "device_class": "switch",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Ưu tiên sạc (PV)",
        "register": H_FUNCTION_ENABLE_1, # 21
        "register_type": "hold",
        "extract": lambda reg: get_bits(reg, 11, 1),
        "compose": lambda orig, value: set_bits(orig, 11, 1, value),
        "icon": "mdi:battery-arrow-up",
        "device_class": "switch",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    # Register 22: H_FUNCTION_ENABLE_2_AND_PV_START_VOLT
    {
        "name": "Phát lên lưới",
        "register": H_FUNCTION_ENABLE_2_AND_PV_START_VOLT, # 22
        "register_type": "hold",
        "extract": lambda reg: get_bits(reg, 15, 1),
        "compose": lambda orig, value: set_bits(orig, 15, 1, value),
        "icon": "mdi:transmission-tower-export",
        "device_class": "switch",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lưới điện",
    },
    # Register 110: H_FUNCTION_ENABLE_3
    {
        "name": "Không phát lưới nhanh",
        "register": H_FUNCTION_ENABLE_3, # 110
        "register_type": "hold",
        "extract": lambda reg: get_bits(reg, 1, 1),
        "compose": lambda orig, value: set_bits(orig, 1, 1, value),
        "icon": "mdi:meter-electric-outline",
        "device_class": "switch",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Lưới nhỏ (Micro-Grid)",
        "register": H_FUNCTION_ENABLE_3, # 110
        "register_type": "hold",
        "extract": lambda reg: get_bits(reg, 2, 1),
        "compose": lambda orig, value: set_bits(orig, 2, 1, value),
        "icon": "mdi:grid",
        "device_class": "switch",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Sạc sau cùng",
        "register": H_FUNCTION_ENABLE_3, # 110
        "register_type": "hold",
        "extract": lambda reg: get_bits(reg, 4, 1),
        "compose": lambda orig, value: set_bits(orig, 4, 1, value),
        "icon": "mdi:battery-arrow-up",
        "device_class": "switch",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Pin",
    },
    {
        "name": "Còi báo",
        "register": H_FUNCTION_ENABLE_3, # 110
        "register_type": "hold",
        "extract": lambda reg: get_bits(reg, 7, 1),
        "compose": lambda orig, value: set_bits(orig, 7, 1, value),
        "icon": "mdi:bell",
        "device_class": "switch",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Dùng tải cùng lúc",
        "register": H_FUNCTION_ENABLE_3, # 110
        "register_type": "hold",
        "extract": lambda reg: get_bits(reg, 10, 1),
        "compose": lambda orig, value: set_bits(orig, 10, 1, value),
        "icon": "mdi:solar-power",
        "device_class": "switch",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Green Mode",
        "register": H_FUNCTION_ENABLE_3, # 110
        "register_type": "hold",
        "extract": lambda reg: get_bits(reg, 14, 1),
        "compose": lambda orig, value: set_bits(orig, 14, 1, value),
        "icon": "mdi:leaf",
        "device_class": "switch",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Eco Mode",
        "register": H_FUNCTION_ENABLE_3, # 110
        "register_type": "hold",
        "extract": lambda reg: get_bits(reg, 15, 1),
        "compose": lambda orig, value: set_bits(orig, 15, 1, value),
        "icon": "mdi:sprout",
        "device_class": "switch",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    # Register 120: H_SYSTEM_ENABLE_2
    {
        "name": "Half Hour AC Charge Start",
        "register": H_SYSTEM_ENABLE_2,   # 120
        "register_type": "hold",
        "extract": lambda reg: get_bits(reg, 0, 1),
        "compose": lambda orig, value: set_bits(orig, 0, 1, value),
        "icon": "mdi:power",
        "device_class": "switch",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    # Register 179: H_FUNCTION_ENABLE_4
    {
        "name": "Volt-Watt Function",
        "register": H_FUNCTION_ENABLE_4, # 179
        "register_type": "hold",
        "extract": lambda reg: get_bits(reg, 4, 1),
        "compose": lambda orig, value: set_bits(orig, 4, 1, value),
        "icon": "mdi:chart-line",
        "device_class": "switch",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lưới điện",
    },
    {
        "name": "Cắt đỉnh tải lưới",
        "register": H_FUNCTION_ENABLE_4, # 179
        "register_type": "hold",
        "extract": lambda reg: get_bits(reg, 7, 1),
        "compose": lambda orig, value: set_bits(orig, 7, 1, value),
        "icon": "mdi:chart-gantt",
        "device_class": "switch",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lưới điện",
    },
    {
        "name": "AC Coupling",
        "register": H_FUNCTION_ENABLE_4, # 179
        "register_type": "hold",
        "extract": lambda reg: get_bits(reg, 11, 1),
        "compose": lambda orig, value: set_bits(orig, 11, 1, value),
        "icon": "mdi:power-plug",
        "device_class": "switch",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "PV Arc Detection",
        "register": H_FUNCTION_ENABLE_4, # 179
        "register_type": "hold",
        "extract": lambda reg: get_bits(reg, 12, 1),
        "compose": lambda orig, value: set_bits(orig, 12, 1, value),
        "icon": "mdi:flash-alert",
        "device_class": "switch",
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Pin mặt trời",
    },
    {
        "name": "On-Grid Always On",
        "register": H_FUNCTION_ENABLE_4, # 179
        "register_type": "hold",
        "extract": lambda reg: get_bits(reg, 15, 1),
        "compose": lambda orig, value: set_bits(orig, 15, 1, value),
        "icon": "mdi:power-cycle",
        "device_class": "switch",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Tải thông minh",
    },
    # Register 233: H_FUNCTION_ENABLE_5
    {
        "name": "Quick Charge Start",
        "register": H_FUNCTION_ENABLE_5, # 233
        "register_type": "hold",
        "extract": lambda reg: get_bits(reg, 0, 1),
        "compose": lambda orig, value: set_bits(orig, 0, 1, value),
        "icon": "mdi:battery-plus",
        "device_class": "switch",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Battery Backup",
        "register": H_FUNCTION_ENABLE_5, # 233
        "register_type": "hold",
        "extract": lambda reg: get_bits(reg, 1, 1),
        "compose": lambda orig, value: set_bits(orig, 1, 1, value),
        "icon": "mdi:battery-heart-variant",
        "device_class": "switch",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Pin",
    },
    {
        "name": "Battery Maintenance",
        "register": H_FUNCTION_ENABLE_5, # 233
        "register_type": "hold",
        "extract": lambda reg: get_bits(reg, 2, 1),
        "compose": lambda orig, value: set_bits(orig, 2, 1, value),
        "icon": "mdi:wrench",
        "device_class": "switch",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Pin",
    },
    {
        "name": "7-Day Schedule Enable",
        "register": H_FUNCTION_ENABLE_5, # 233
        "register_type": "hold",
        "extract": lambda reg: get_bits(reg, 3, 1),
        "compose": lambda orig, value: set_bits(orig, 3, 1, value),
        "icon": "mdi:calendar-check",
        "device_class": "switch",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "WattNode CT1 Direction",
        "register": H_WATTNODE_CT_DIRECTIONS,
        "register_type": "hold",
        "extract": lambda reg: get_bits(reg, 0, 1),
        "compose": lambda orig, value: set_bits(orig, 0, 1, value),
        "icon": "mdi:arrow-left-right",
        "device_class": "switch",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "WattNode CT2 Direction",
        "register": H_WATTNODE_CT_DIRECTIONS,
        "register_type": "hold",
        "extract": lambda reg: get_bits(reg, 1, 1),
        "compose": lambda orig, value: set_bits(orig, 1, 1, value),
        "icon": "mdi:arrow-left-right",
        "device_class": "switch",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "WattNode CT3 Direction",
        "register": H_WATTNODE_CT_DIRECTIONS,
        "register_type": "hold",
        "extract": lambda reg: get_bits(reg, 2, 1),
        "compose": lambda orig, value: set_bits(orig, 2, 1, value),
        "icon": "mdi:arrow-left-right",
        "device_class": "switch",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
]