from ..constants.hold_registers import *

TIME_TYPES = [
    {
        "name": "Giờ bắt đầu sạc AC",
        "register": H_AC_CHARGE_START_TIME, # 68
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Giờ kết thúc sạc AC",
        "register": H_AC_CHARGE_END_TIME, # 69
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Giờ bắt đầu sạc AC 1",
        "register": H_AC_CHARGE_START_TIME_1, # 70
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Giờ kết thúc sạc AC 1",
        "register": H_AC_CHARGE_END_TIME_1, # 71
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Giờ bắt đầu sạc AC 2",
        "register": H_AC_CHARGE_START_TIME_2, # 72
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Giờ kết thúc sạc AC 2",
        "register": H_AC_CHARGE_END_TIME_2, # 73
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Giờ bắt đầu ưu tiên AC",
        "register": H_AC_FIRST_START_TIME, # 152
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Giờ kết thúc ưu tiên AC",
        "register": H_AC_FIRST_END_TIME, # 153
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Giờ bắt đầu ưu tiên AC 1",
        "register": H_AC_FIRST_START_TIME_1, # 154
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Giờ kết thúc ưu tiên AC 1",
        "register": H_AC_FIRST_END_TIME_1, # 155
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Giờ bắt đầu cắt đỉnh",
        "register": H_PEAK_SHAVING_START_TIME, # 209
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lưới điện",
    },
    {
        "name": "Giờ kết thúc cắt đỉnh",
        "register": H_PEAK_SHAVING_END_TIME, # 210
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lưới điện",
    },
    {
        "name": "Giờ bắt đầu cắt đỉnh 1",
        "register": H_PEAK_SHAVING_START_TIME_1, # 211
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lưới điện",
    },
    {
        "name": "Giờ kết thúc cắt đỉnh 1",
        "register": H_PEAK_SHAVING_END_TIME_1, # 212
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lưới điện",
    },
    {
        "name": "Giờ bật máy phát",
        "register": H_GEN_START_TIME,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:engine-outline",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Máy phát",
    },
    {
        "name": "Giờ tắt máy phát",
        "register": H_GEN_END_TIME,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:engine-off-outline",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Máy phát",
    },
    {
        "name": "Giờ bật máy phát 1",
        "register": H_GEN_START_TIME_1,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:engine-outline",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Máy phát",
    },
    {
        "name": "Giờ tắt máy phát 1",
        "register": H_GEN_END_TIME_1,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:engine-off-outline",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Máy phát",
    },
    {
        "name": "Giờ bắt đầu xả cưỡng bức",
        "register": H_FORCED_DISCHARGE_START_TIME, # 84
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Giờ kết thúc xả cưỡng bức",
        "register": H_FORCED_DISCHARGE_END_TIME, # 85
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Giờ bắt đầu xả cưỡng bức 1",
        "register": H_FORCED_DISCHARGE_START_TIME_1, # 86
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Giờ kết thúc xả cưỡng bức 1",
        "register": H_FORCED_DISCHARGE_END_TIME_1, # 87
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Giờ bắt đầu xả cưỡng bức 2",
        "register": H_FORCED_DISCHARGE_START_TIME_2, # 88
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Giờ kết thúc xả cưỡng bức 2",
        "register": H_FORCED_DISCHARGE_END_TIME_2, # 89
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },

    # ===========================================================================================
    # 7-DAY SCHEDULING TIME ENTITIES (Registers 500-723)
    # ===========================================================================================

    # --- AC Charge Schedule Time Entities ---

    {
        "name": "Giờ bắt đầu sạc AC 1 T2",
        "register": H_AC_CHG_TIME1_START_MON,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc sạc AC 1 T2",
        "register": H_AC_CHG_TIME1_END_MON,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu sạc AC 2 T2",
        "register": H_AC_CHG_TIME2_START_MON,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc sạc AC 2 T2",
        "register": H_AC_CHG_TIME2_END_MON,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu sạc AC 1 T3",
        "register": H_AC_CHG_TIME1_START_TUE,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc sạc AC 1 T3",
        "register": H_AC_CHG_TIME1_END_TUE,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu sạc AC 2 T3",
        "register": H_AC_CHG_TIME2_START_TUE,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc sạc AC 2 T3",
        "register": H_AC_CHG_TIME2_END_TUE,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu sạc AC 1 T4",
        "register": H_AC_CHG_TIME1_START_WED,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc sạc AC 1 T4",
        "register": H_AC_CHG_TIME1_END_WED,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu sạc AC 2 T4",
        "register": H_AC_CHG_TIME2_START_WED,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc sạc AC 2 T4",
        "register": H_AC_CHG_TIME2_END_WED,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu sạc AC 1 T5",
        "register": H_AC_CHG_TIME1_START_THU,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc sạc AC 1 T5",
        "register": H_AC_CHG_TIME1_END_THU,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu sạc AC 2 T5",
        "register": H_AC_CHG_TIME2_START_THU,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc sạc AC 2 T5",
        "register": H_AC_CHG_TIME2_END_THU,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu sạc AC 1 T6",
        "register": H_AC_CHG_TIME1_START_FRI,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc sạc AC 1 T6",
        "register": H_AC_CHG_TIME1_END_FRI,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu sạc AC 2 T6",
        "register": H_AC_CHG_TIME2_START_FRI,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc sạc AC 2 T6",
        "register": H_AC_CHG_TIME2_END_FRI,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu sạc AC 1 T7",
        "register": H_AC_CHG_TIME1_START_SAT,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc sạc AC 1 T7",
        "register": H_AC_CHG_TIME1_END_SAT,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu sạc AC 2 T7",
        "register": H_AC_CHG_TIME2_START_SAT,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc sạc AC 2 T7",
        "register": H_AC_CHG_TIME2_END_SAT,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu sạc AC 1 CN",
        "register": H_AC_CHG_TIME1_START_SUN,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc sạc AC 1 CN",
        "register": H_AC_CHG_TIME1_END_SUN,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu sạc AC 2 CN",
        "register": H_AC_CHG_TIME2_START_SUN,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc sạc AC 2 CN",
        "register": H_AC_CHG_TIME2_END_SUN,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },

    # --- Forced Charge Schedule Time Entities ---

    {
        "name": "Giờ bắt đầu sạc cưỡng bức 1 T2",
        "register": H_FORCED_CHG_TIME1_START_MON,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc sạc cưỡng bức 1 T2",
        "register": H_FORCED_CHG_TIME1_END_MON,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu sạc cưỡng bức 2 T2",
        "register": H_FORCED_CHG_TIME2_START_MON,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc sạc cưỡng bức 2 T2",
        "register": H_FORCED_CHG_TIME2_END_MON,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu sạc cưỡng bức 1 T3",
        "register": H_FORCED_CHG_TIME1_START_TUE,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc sạc cưỡng bức 1 T3",
        "register": H_FORCED_CHG_TIME1_END_TUE,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu sạc cưỡng bức 2 T3",
        "register": H_FORCED_CHG_TIME2_START_TUE,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc sạc cưỡng bức 2 T3",
        "register": H_FORCED_CHG_TIME2_END_TUE,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu sạc cưỡng bức 1 T4",
        "register": H_FORCED_CHG_TIME1_START_WED,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc sạc cưỡng bức 1 T4",
        "register": H_FORCED_CHG_TIME1_END_WED,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu sạc cưỡng bức 2 T4",
        "register": H_FORCED_CHG_TIME2_START_WED,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc sạc cưỡng bức 2 T4",
        "register": H_FORCED_CHG_TIME2_END_WED,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu sạc cưỡng bức 1 T5",
        "register": H_FORCED_CHG_TIME1_START_THU,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc sạc cưỡng bức 1 T5",
        "register": H_FORCED_CHG_TIME1_END_THU,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu sạc cưỡng bức 2 T5",
        "register": H_FORCED_CHG_TIME2_START_THU,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc sạc cưỡng bức 2 T5",
        "register": H_FORCED_CHG_TIME2_END_THU,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu sạc cưỡng bức 1 T6",
        "register": H_FORCED_CHG_TIME1_START_FRI,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc sạc cưỡng bức 1 T6",
        "register": H_FORCED_CHG_TIME1_END_FRI,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu sạc cưỡng bức 2 T6",
        "register": H_FORCED_CHG_TIME2_START_FRI,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc sạc cưỡng bức 2 T6",
        "register": H_FORCED_CHG_TIME2_END_FRI,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu sạc cưỡng bức 1 T7",
        "register": H_FORCED_CHG_TIME1_START_SAT,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc sạc cưỡng bức 1 T7",
        "register": H_FORCED_CHG_TIME1_END_SAT,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu sạc cưỡng bức 2 T7",
        "register": H_FORCED_CHG_TIME2_START_SAT,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc sạc cưỡng bức 2 T7",
        "register": H_FORCED_CHG_TIME2_END_SAT,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu sạc cưỡng bức 1 CN",
        "register": H_FORCED_CHG_TIME1_START_SUN,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc sạc cưỡng bức 1 CN",
        "register": H_FORCED_CHG_TIME1_END_SUN,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu sạc cưỡng bức 2 CN",
        "register": H_FORCED_CHG_TIME2_START_SUN,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc sạc cưỡng bức 2 CN",
        "register": H_FORCED_CHG_TIME2_END_SUN,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },

    # --- Forced Discharge Schedule Time Entities ---

    {
        "name": "Giờ bắt đầu xả cưỡng bức 1 T2",
        "register": H_FORCED_DISCHG_TIME1_START_MON,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc xả cưỡng bức 1 T2",
        "register": H_FORCED_DISCHG_TIME1_END_MON,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu xả cưỡng bức 2 T2",
        "register": H_FORCED_DISCHG_TIME2_START_MON,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc xả cưỡng bức 2 T2",
        "register": H_FORCED_DISCHG_TIME2_END_MON,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu xả cưỡng bức 1 T3",
        "register": H_FORCED_DISCHG_TIME1_START_TUE,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc xả cưỡng bức 1 T3",
        "register": H_FORCED_DISCHG_TIME1_END_TUE,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu xả cưỡng bức 2 T3",
        "register": H_FORCED_DISCHG_TIME2_START_TUE,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc xả cưỡng bức 2 T3",
        "register": H_FORCED_DISCHG_TIME2_END_TUE,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu xả cưỡng bức 1 T4",
        "register": H_FORCED_DISCHG_TIME1_START_WED,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc xả cưỡng bức 1 T4",
        "register": H_FORCED_DISCHG_TIME1_END_WED,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu xả cưỡng bức 2 T4",
        "register": H_FORCED_DISCHG_TIME2_START_WED,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc xả cưỡng bức 2 T4",
        "register": H_FORCED_DISCHG_TIME2_END_WED,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu xả cưỡng bức 1 T5",
        "register": H_FORCED_DISCHG_TIME1_START_THU,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc xả cưỡng bức 1 T5",
        "register": H_FORCED_DISCHG_TIME1_END_THU,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu xả cưỡng bức 2 T5",
        "register": H_FORCED_DISCHG_TIME2_START_THU,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc xả cưỡng bức 2 T5",
        "register": H_FORCED_DISCHG_TIME2_END_THU,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu xả cưỡng bức 1 T6",
        "register": H_FORCED_DISCHG_TIME1_START_FRI,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc xả cưỡng bức 1 T6",
        "register": H_FORCED_DISCHG_TIME1_END_FRI,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu xả cưỡng bức 2 T6",
        "register": H_FORCED_DISCHG_TIME2_START_FRI,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc xả cưỡng bức 2 T6",
        "register": H_FORCED_DISCHG_TIME2_END_FRI,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu xả cưỡng bức 1 T7",
        "register": H_FORCED_DISCHG_TIME1_START_SAT,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc xả cưỡng bức 1 T7",
        "register": H_FORCED_DISCHG_TIME1_END_SAT,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu xả cưỡng bức 2 T7",
        "register": H_FORCED_DISCHG_TIME2_START_SAT,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc xả cưỡng bức 2 T7",
        "register": H_FORCED_DISCHG_TIME2_END_SAT,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu xả cưỡng bức 1 CN",
        "register": H_FORCED_DISCHG_TIME1_START_SUN,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc xả cưỡng bức 1 CN",
        "register": H_FORCED_DISCHG_TIME1_END_SUN,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu xả cưỡng bức 2 CN",
        "register": H_FORCED_DISCHG_TIME2_START_SUN,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc xả cưỡng bức 2 CN",
        "register": H_FORCED_DISCHG_TIME2_END_SUN,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },

    # --- Peak Shaving Schedule Time Entities ---

    {
        "name": "Giờ bắt đầu cắt đỉnh 1 T2",
        "register": H_PEAK_SHAV_TIME1_START_MON,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc cắt đỉnh 1 T2",
        "register": H_PEAK_SHAV_TIME1_END_MON,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu cắt đỉnh 2 T2",
        "register": H_PEAK_SHAV_TIME2_START_MON,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc cắt đỉnh 2 T2",
        "register": H_PEAK_SHAV_TIME2_END_MON,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu cắt đỉnh 1 T3",
        "register": H_PEAK_SHAV_TIME1_START_TUE,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc cắt đỉnh 1 T3",
        "register": H_PEAK_SHAV_TIME1_END_TUE,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu cắt đỉnh 2 T3",
        "register": H_PEAK_SHAV_TIME2_START_TUE,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc cắt đỉnh 2 T3",
        "register": H_PEAK_SHAV_TIME2_END_TUE,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu cắt đỉnh 1 T4",
        "register": H_PEAK_SHAV_TIME1_START_WED,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc cắt đỉnh 1 T4",
        "register": H_PEAK_SHAV_TIME1_END_WED,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu cắt đỉnh 2 T4",
        "register": H_PEAK_SHAV_TIME2_START_WED,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc cắt đỉnh 2 T4",
        "register": H_PEAK_SHAV_TIME2_END_WED,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu cắt đỉnh 1 T5",
        "register": H_PEAK_SHAV_TIME1_START_THU,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc cắt đỉnh 1 T5",
        "register": H_PEAK_SHAV_TIME1_END_THU,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu cắt đỉnh 2 T5",
        "register": H_PEAK_SHAV_TIME2_START_THU,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc cắt đỉnh 2 T5",
        "register": H_PEAK_SHAV_TIME2_END_THU,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu cắt đỉnh 1 T6",
        "register": H_PEAK_SHAV_TIME1_START_FRI,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc cắt đỉnh 1 T6",
        "register": H_PEAK_SHAV_TIME1_END_FRI,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu cắt đỉnh 2 T6",
        "register": H_PEAK_SHAV_TIME2_START_FRI,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc cắt đỉnh 2 T6",
        "register": H_PEAK_SHAV_TIME2_END_FRI,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu cắt đỉnh 1 T7",
        "register": H_PEAK_SHAV_TIME1_START_SAT,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc cắt đỉnh 1 T7",
        "register": H_PEAK_SHAV_TIME1_END_SAT,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu cắt đỉnh 2 T7",
        "register": H_PEAK_SHAV_TIME2_START_SAT,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc cắt đỉnh 2 T7",
        "register": H_PEAK_SHAV_TIME2_END_SAT,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu cắt đỉnh 1 CN",
        "register": H_PEAK_SHAV_TIME1_START_SUN,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc cắt đỉnh 1 CN",
        "register": H_PEAK_SHAV_TIME1_END_SUN,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ bắt đầu cắt đỉnh 2 CN",
        "register": H_PEAK_SHAV_TIME2_START_SUN,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    {
        "name": "Giờ kết thúc cắt đỉnh 2 CN",
        "register": H_PEAK_SHAV_TIME2_END_SUN,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Lịch trình",
    },
    # --- Charge First Times ---
    {
        "name": "Giờ bắt đầu ưu tiên sạc",
        "register": H_CHARGE_FIRST_START_TIME,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Pin",
    },
    {
        "name": "Giờ kết thúc ưu tiên sạc",
        "register": H_CHARGE_FIRST_END_TIME,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Pin",
    },
    {
        "name": "Giờ bắt đầu ưu tiên sạc 1",
        "register": H_CHARGE_FIRST_START_TIME_1,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Pin",
    },
    {
        "name": "Giờ kết thúc ưu tiên sạc 1",
        "register": H_CHARGE_FIRST_END_TIME_1,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Pin",
    },
    {
        "name": "Giờ bắt đầu ưu tiên sạc 2",
        "register": H_CHARGE_FIRST_START_TIME_2,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Pin",
    },
    {
        "name": "Giờ kết thúc ưu tiên sạc 2",
        "register": H_CHARGE_FIRST_END_TIME_2,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Pin",
    },

    # --- AC First Period 2 Times ---
    {
        "name": "Giờ bắt đầu ưu tiên AC 2",
        "register": H_AC_FIRST_START_TIME_2,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Giờ kết thúc ưu tiên AC 2",
        "register": H_AC_FIRST_END_TIME_2,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },


]
