WARNING_CODES = {
    0: "Mất giao tiếp với pin",
    1: "Lỗi giao tiếp AFCI",
    2: "Nhiệt độ pin quá thấp",
    3: "Mất giao tiếp với đồng hồ điện",
    4: "Pin không thể sạc/xả",
    5: "Kiểm tra tự động thất bại",
    6: "RSD đang kích hoạt",
    7: "Lỗi giao tiếp LCD",
    8: "Phiên bản phần mềm không khớp",
    9: "Quạt bị kẹt",
    10: "Quá tải lưới điện",
    11: "Số thiết bị phụ song song vượt giới hạn",
    12: "MOS đảo chiều pin bất thường",
    13: "Nhiệt độ tản nhiệt ngoài phạm vi",
    14: "Nhiều thiết bị chính được cài trong hệ thống song song",
    15: "Pin đảo chiều",
    16: "Không kết nối lưới",
    17: "Điện áp lưới ngoài phạm vi",
    18: "Tần số lưới ngoài phạm vi",
    20: "Điện trở cách điện thấp",
    21: "Dòng rò quá cao",
    22: "DCI vượt tiêu chuẩn",
    23: "Ngắn mạch PV",
    25: "Quá áp pin",
    26: "Sụt áp pin",
    27: "Pin hở mạch",
    28: "Quá tải EPS",
    29: "Điện áp EPS cao",
    30: "Đồng hồ điện đấu ngược",
    31: "DCV vượt tiêu chuẩn",
}
